### PR TITLE
Fix adding account to empty file

### LINKED ISSUE #3379: Adding account to empty file fails
### Select Tool

sncast

### Foundry Version

0.43.0

### What operating system are you using?

MacOS

### What system architecture are you using?

arm

### Issue Description

To reproduce:
1. Create an empty file
2. Execute `account create` or `account import` with passing newly created file as `--accounts-file`

### Command Line Output

```
command: account create
error: Failed to parse accounts file at = ./my_accounts.json
```

### PR DESCRIPTION
**Pull request by franciszekjob**
Closes #3379

## Introduced changes

Fix `sncast account create` when file specified by `--accounts-file` is empty

## Checklist

- [x] Linked relevant issue
- [x] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

### CODE REVIEW

File: crates/sncast/tests/e2e/account/create.rs [hunk 1]
```diff
@@ -870,3 +870,30 @@ pub async fn test_happy_case_deployment_fee_message() {
         "message: Account successfully created but it needs to be deployed. The estimated deployment fee is 0.000836288000000000 STRK. Prefund the account to cover deployment transaction fee",
     );
 }
+
+#[tokio::test]
+pub async fn test_happy_case_accounts_file_empty() {
+    let temp_dir = tempdir().expect("Unable to create a temporary directory");
```
Comment (kkawula) [inline crates/sncast/tests/e2e/account/create.rs:832]: I suppose we can use `.unwrap()` in the tests

File: CHANGELOG.md [hunk 2]
```diff
@@ -30,6 +30,10 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 
 ### Cast
 
+#### Fixed
+
+- bug where `account create` would fail with a parsing error if the file specified by `--accounts-file` was empty
```
Comment (kkawula) [inline CHANGELOG.md]:
```suggestion
- `account create` won't fail while parsing an empty accounts file
```

**Review by kkawula — APPROVED** [review]

File: crates/sncast/tests/e2e/account/create.rs (hunk 1 above)
Comment (franciszekjob) [reply crates/sncast/tests/e2e/account/create.rs:832]: It's the same as in other tests so let's leave it as it is.

File: CHANGELOG.md (hunk 2 above)
Comment (franciszekjob) [reply CHANGELOG.md]: Actually I like `bug where `account create` raised an error if the file specified by `--accounts-file` was empty` the most

File: crates/sncast/tests/e2e/account/deploy.rs [hunk 3]
```diff
@@ -54,8 +54,9 @@ pub async fn test_happy_case(class_hash: &str, account_type: &str) {
     assert!(stdout_str.contains("account deploy"));
     assert!(stdout_str.contains("transaction_hash"));
 
-    let contents = fs::read_to_string(tempdir.path().join(accounts_file)).unwrap();
-    let items: Value = serde_json::from_str(&contents).expect("Failed to parse accounts file at ");
+    let path = camino::Utf8PathBuf::from_path_buf(tempdir.path().join(accounts_file))
```
Comment (ddoktorski) [inline crates/sncast/tests/e2e/account/deploy.rs]: nit:
Maybe import `camino::Utf8PathBuf`
```suggestion
    let path = Utf8PathBuf::from_path_buf(tempdir.path().join(accounts_file))
```

**Review by ddoktorski — APPROVED** [review]
