### PR TITLE
Fix parsing private key on when importing account

### LINKED ISSUE #2877: Fails to parse private key when importing with `sncast import`
### Which component is your bug related to?

sncast

### Foundry Version

0.36.0

### What operating system are you using?

Linux

### What system architecture are you using?

x86

### What happened

Importing an account, and providing a private key, for example,
```
0x01c667c232b8ee6b035b98d2294b915e12b74080d4264f829a2409b354366b6d
```

results in an error 
```
error: Failed to parse value 0x01c667c232b8ee6b035b98d2294b915e12b74080d4264f829a2409b354366b6d to felt. Invalid hex value was passed
```

Importing the same key without the leading zero, or when directly providing it in the command line, does work

### Trace

```
sncast account import --address 0xxxxxxxxx --type braavos --url http://192.168.1.45:9235 --name braavos_6 
Type in your private key and press enter: 
command: account import
error: Failed to parse value 0x01c667c232b8ee6b035b98d2294b915e12b74080d4264f829a2409b354366b6d to felt. Invalid hex value was passed
``` 

### Is there an existing issue for this?

- [ ] I have searched the existing issues and verified no issue exits for this problem.

### PR DESCRIPTION
**Pull request by franciszekjob**
Closes #2877

## Introduced changes

Refactor `parse_input_to_felt` to use `Felt::try_from_hex_str` instead of regex.

## Checklist

- [x] Linked relevant issue
- [x] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

### CODE REVIEW

File: crates/sncast/src/starknet_commands/account/import.rs [hunk 1]
```diff
@@ -181,8 +181,9 @@ fn get_private_key_from_file(file_path: &Utf8PathBuf) -> Result<Felt> {
 }
 
 fn parse_input_to_felt(input: &String) -> Result<Felt> {
-    // Regex is from spec https://github.com/starkware-libs/starknet-specs/blob/6d88b7399f56260ece3821c71f9ce53ec55f830b/api/starknet_api_openrpc.json#L1303
-    let felt_re = Regex::new(r"^0x(0|[a-fA-F1-9]{1}[a-fA-F0-9]{0,62})$").unwrap();
+    // Original regex from spec https://github.com/starkware-libs/starknet-specs/blob/6d88b7399f56260ece3821c71f9ce53ec55f830b/api/starknet_api_openrpc.json#L1303
```
Comment (ksew1) [inline crates/sncast/src/starknet_commands/account/import.rs:184]: Why don't we use `infer_format_and_parse`? Also, this regex only checks if the `String` is in hexadecimal format, which is already verified by `try_from_hex_str`. A simpler version would be:  
  
```rs
 fn parse_input_to_felt(value: &str) -> Result<Felt> {
   Felt::try_from_hex_str(value)
         .or_else(|_| Felt::try_from_dec_str(value))
         .with_context(|| format!("Failed to parse the value {value} as a felt"))
 }  
 ```

Comment (franciszekjob) [reply crates/sncast/src/starknet_commands/account/import.rs:184]: I like the second suggestion more, as `infer_format_and_parse` returns result with vector of felts.

File: crates/sncast/src/starknet_commands/account/import.rs [hunk 2]
```diff
@@ -181,19 +180,9 @@ fn get_private_key_from_file(file_path: &Utf8PathBuf) -> Result<Felt> {
 }
 
 fn parse_input_to_felt(input: &String) -> Result<Felt> {
```
Comment (ksew1) [inline crates/sncast/src/starknet_commands/account/import.rs:182]:
```suggestion
fn parse_input_to_felt(input: &str) -> Result<Felt> {
```

**Review by ksew1 — COMMENTED** [review]
You need to fix error messages in tests

**Review by ksew1 — APPROVED** [review]

File: crates/sncast/src/starknet_commands/account/import.rs [hunk 3]
```diff
@@ -210,8 +199,17 @@ mod tests {
 
     #[test]
     fn test_parse_hex_str() {
+        let hex_str = "0x0000000000000000000000000000000000000000000000000000000000000001";
+        let result = parse_input_to_felt(hex_str);
+
+        assert!(result.is_ok());
```
Comment (ddoktorski) [inline crates/sncast/src/starknet_commands/account/import.rs:205]: nit: This assert is redundant

**Review by ddoktorski — APPROVED** [review]
