### PR TITLE
Emit error if parameters without `#[fuzzer]` attribute

### LINKED ISSUE #3019: Catch error if #[fuzzer] attribute wasn't provided for fuzz test
### Which component is your bug related to?

snforge

### Foundry Version

0.38.0

### What operating system are you using?

MacOS

### What system architecture are you using?

arm

### What happened

```
#[test]
fn test_single_send_fuzz(transfer_value: u256) {
```
missing #[fuzzer]

### Trace

thread '<unnamed>' panicked at crates/runtime/src/lib.rs:181:80:
index out of bounds: the len is 1 but the index is 1
stack backtrace:
   0:        0x1038e13d4 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h6e25c13836847e70
   1:        0x103902bf8 - core::fmt::write::h37cdb50ab8af3d55
   2:        0x1038dd858 - std::io::Write::write_fmt::hd4c273f34c4c0a33
   3:        0x1038e1288 - std::sys::backtrace::BacktraceLock::print::h1df7364dde63dc75
   4:        0x1038e277c - std::panicking::default_hook::{{closure}}::h646e398272c5759a
   5:        0x1038e2570 - std::panicking::default_hook::hf65fd28e95db7176
   6:        0x1038e30c8 - std::panicking::rust_panic_with_hook::hc9e2ec2a12b10e12
   7:        0x1038e2c70 - std::panicking::begin_panic_handler::{{closure}}::h3b6449e2eb83bf4c
   8:        0x1038e1888 - std::sys::backtrace::__rust_end_short_backtrace::h38d85099ddd107a3
   9:        0x1038e2928 - _rust_begin_unwind
  10:        0x1039643bc - core::panicking::panic_fmt::hd4003258f6ab7b29
  11:        0x10396453c - core::panicking::panic_bounds_check::h4fadfa91bf056b25
  12:        0x10320d844 - <runtime::StarknetRuntime as cairo_vm::hint_processor::hint_processor_definition::HintProcessorLogic>::execute_hint::hee4b81a0bc1a410b
  13:        0x10357b494 - cairo_vm::vm::vm_core::VirtualMachine::step::h9d7c7836c448a172
  14:        0x103554a30 - cairo_vm::vm::runners::cairo_runner::CairoRunner::run_until_pc::h207e0be1d045d9d0
  15:        0x10304c784 - cairo_lang_runner::casm_run::run_function_with_runner::h2b698151830859e4
  16:        0x103071d0c - forge_runner::running::casm::run_assembled_program::hb642388222cd21c6
  17:        0x10307208c - forge_runner::running::config_run::run_config_pass::h66b3e49034a82000
  18:        0x10305cb48 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::h6f3ce5412269f2f0
  19:        0x102ffbc08 - <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend::hab35646d9790d3fc
  20:        0x103018754 - rayon::iter::plumbing::bridge_producer_consumer::helper::h10d63a18098e6001
  21:        0x10305a834 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::had754faec24460bd
  22:        0x103933df4 - rayon_core::registry::WorkerThread::wait_until_cold::h5a5ad8dcfff52b07
  23:        0x1034cb2cc - rayon_core::registry::ThreadBuilder::run::hf219ad52735e33d8
  24:        0x1034d09d0 - std::sys::backtrace::__rust_begin_short_backtrace::ha9ffc9359cedc377
  25:        0x1034cf044 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc7ca45c92de07944
  26:        0x1038e791c - std::sys::pal::unix::thread::Thread::new::thread_start::h02b173395cbbc15c
  27:        0x181c342e4 - __pthread_deallocate

### Is there an existing issue for this?

- [x] I have searched the existing issues and verified no issue exits for this problem.

### PR DESCRIPTION
**Pull request by ddoktorski**
Closes #3019

## Introduced changes

- Emit an error if function has the `#[test]` attribute, defined parameters and no `#[fuzzer]` attribute

## Checklist

- [X] Linked relevant issue
- [X] Updated relevant documentation
- [X] Added relevant tests
- [X] Performed self-review of the code
- [X] Added changes to `CHANGELOG.md`

### CODE REVIEW

File: crates/snforge-scarb-plugin/tests/integration/multiple_attributes.rs [hunk 1]
```diff
@@ -155,36 +155,16 @@ fn works_with_fuzzer_config_wrapper() {
...
-                    }
-                    .serialize(ref data);
-
-                    starknet::testing::cheatcode::<'set_config_available_gas'>(data.span());
-
-                    return;
-                }
-            }
+    // Cannot apply `test` attribute here as it would cause an error
+    // due to the function having a parameter
```
Comment (kkawula) [inline crates/snforge-scarb-plugin/tests/integration/multiple_attributes.rs:159]: What about adding `#fuzzer` token? Then this test can remain unchanged?

**Review by kkawula — APPROVED** [review]
I suppose we should address cases when it is alone `#[fuzzer]`, `#[should_panic]` etc. bcs forge skip it without any warning. It can be a field to make mistakes.

File: crates/snforge-scarb-plugin/tests/integration/multiple_attributes.rs (hunk 1 above)
Comment (ddoktorski) [reply crates/snforge-scarb-plugin/tests/integration/multiple_attributes.rs:159]: This test is meant to simulate a real workflow applying in this order `available_gas` -> `test` -> `fuzzer_config` -> `fuzzer_wrapper`. While writing this test, I specifically wanted to ensure that everything on the fuzzer side works correctly when there are test attributes on the function (executable and internal config statement). Tests specifically for the `#[fuzzer]` attribute are in other places.

File: crates/snforge-scarb-plugin/src/attributes/test.rs [hunk 2]
```diff
@@ -66,3 +68,36 @@ fn test_internal(
 fn get_forge_test_filter() -> Result<String, VarError> {
     env::var("SNFORGE_TEST_FILTER")
 }
+
+fn ensure_parameters_only_with_fuzzer_attribute(
```
Comment (ksew1) [inline crates/snforge-scarb-plugin/src/attributes/test.rs:72]: What about this

```rs
fn ensure_parameters_only_with_fuzzer_attribute(
    db: &dyn SyntaxGroup,
    func: &FunctionWithBody,
) -> Result<(), Diagnostic> {
    const FUZZER_ATTRIBUTES: [&str; 3] = [
        FuzzerCollector::ATTR_NAME,
        FuzzerWrapperCollector::ATTR_NAME,
        FuzzerConfigCollector::ATTR_NAME,
    ];

    let no_fuzzer_attribute = func
        .attributes(db)
        .elements(db)
        .iter()
        .any(|attr| {
            FUZZER_ATTRIBUTES.contains(
                &attr
                    .attr(db)
                    .as_syntax_node()
                    .get_text_without_trivia(db)
                    .as_str(),
            )
        })
        .not();

    let has_parameters = func
        .declaration(db)
        .signature(db)
        .parameters(db)
        .elements(db)
        .is_empty()
        .not();

    if has_parameters && no_fuzzer_attribute {
        Err(TestCollector::error(
            "function with parameters must have #[fuzzer] attribute",
        ))
    } else {
        Ok(())
    }
}

```

I had hard time reading that if 😄

Comment (ksew1) [reply crates/snforge-scarb-plugin/src/attributes/test.rs:72]: Or with functions for lazy computing:

```rs
fn ensure_parameters_only_with_fuzzer_attribute(
    db: &dyn SyntaxGroup,
    func: &FunctionWithBody,
) -> Result<(), Diagnostic> {
    if has_parameters(db, func) && no_fuzzer_attribute(db, func) {
        Err(TestCollector::error(
            "function with parameters must have #[fuzzer] attribute",
        ))
    } else {
        Ok(())
    }
}

fn has_parameters(db: &dyn SyntaxGroup, func: &FunctionWithBody) -> bool {
    func.declaration(db)
        .signature(db)
        .parameters(db)
        .elements(db)
        .is_empty()
        .not()
}

fn no_fuzzer_attribute(db: &dyn SyntaxGroup, func: &FunctionWithBody) -> bool {
    const FUZZER_ATTRIBUTES: [&str; 3] = [
        FuzzerCollector::ATTR_NAME,
        FuzzerWrapperCollector::ATTR_NAME,
        FuzzerConfigCollector::ATTR_NAME,
    ];

    func.attributes(db)
        .elements(db)
        .iter()
        .any(|attr| {
            FUZZER_ATTRIBUTES.contains(
                &attr
                    .attr(db)
                    .as_syntax_node()
                    .get_text_without_trivia(db)
                    .as_str(),
            )
        })
        .not()
}
```

File: crates/snforge-scarb-plugin/src/attributes/test.rs [hunk 3]
```diff
@@ -66,3 +69,47 @@ fn test_internal(
...
+    db: &dyn SyntaxGroup,
+    func: &FunctionWithBody,
+) -> Result<(), Diagnostic> {
+    if has_parameters(db, func) && no_fuzzer_attribute(db, func) {
+        Err(TestCollector::error(
+            "function with parameters must have #[fuzzer] attribute",
+        ))?;
```
Comment (ksew1) [inline crates/snforge-scarb-plugin/src/attributes/test.rs:80]: Nit: Using `?` rust adds call to `From` which is not needed here:

We can do this instead:

```rs
fn ensure_parameters_only_with_fuzzer_attribute(
    db: &dyn SyntaxGroup,
    func: &FunctionWithBody,
) -> Result<(), Diagnostic> {
    if has_parameters(db, func) && no_fuzzer_attribute(db, func) {
        return Err(TestCollector::error(
            "function with parameters must have #[fuzzer] attribute",
        ));
    }

    Ok(())
}
```

or this

```rs
fn ensure_parameters_only_with_fuzzer_attribute(
    db: &dyn SyntaxGroup,
    func: &FunctionWithBody,
) -> Result<(), Diagnostic> {
    if has_parameters(db, func) && no_fuzzer_attribute(db, func) {
        Err(TestCollector::error(
            "function with parameters must have #[fuzzer] attribute",
        ))
    } else {
        Ok(())
    }
}
```

**Review by ksew1 — APPROVED** [review]
LGTM!

**Review by cptartur — COMMENTED** [review]
Looked at outputs only and they look good.

Ideally we could have some sanity assert in `running.rs` as well, but it would not be trivial because test case there will have some arguments for builtins etc.
