### PR TITLE
Fix duplicated short options

### LINKED ISSUE #2538: `sncast` CLI panics using debug profile
### Which components does the task require to be changed? (think hard pls)

sncast

### Description

This was undetected using our CI because we are running with `--release` flag which doesn't do debug assertions. However, when running tests just with `sncast test`, cast fails with

```
Command add: Short option names must be unique for each argument, but '-a' is in use by both 'address' and 'account'
```

This is due to conflict introduced by global arguments.

- [ ] Resolve the conflict so it no longer fails
- [ ] Update tests in CI so we detect this kind of problems in the future. Probably this can be used to detect/test these https://docs.rs/clap/latest/clap/struct.Command.html#method.debug_assert

### PR DESCRIPTION
**Pull request by franciszekjob**
Closes #2538 

## Introduced changes

- Remove short option for `--accounts-file` flag.
- Change short option to `-d` for `--contract-address` flag.
- Add step to run one test in debug profile. This is because clap can suppress some errors in the release profile due to removed debug assertions.

## Checklist

- [x] Linked relevant issue
- [x] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

### CODE REVIEW

File: crates/sncast/src/starknet_commands/call.rs [hunk 1]
```diff
@@ -11,7 +11,7 @@ use starknet::providers::{JsonRpcClient, Provider};
 #[command(about = "Call a contract instance on Starknet", long_about = None)]
 pub struct Call {
     /// Address of the called contract (hex)
-    #[clap(short = 'a', long)]
+    #[clap(short = 'd', long)]
```
Comment (cptartur) [inline crates/sncast/src/starknet_commands/call.rs:14]: Maybe `-c` would make more sense? From `c`ontract

File: crates/sncast/src/main.rs [hunk 2]
```diff
@@ -76,7 +76,7 @@ struct Cli {
     account: Option<String>,
 
     /// Path to the file holding accounts info
-    #[clap(short = 'f', long = "accounts-file", global = true)]
+    #[clap(long = "accounts-file", global = true)]
```
Comment (franciszekjob) [inline crates/sncast/src/main.rs:79]: note: imo it's better to get rid of short option if we can't use `f` or `a` (they are take by other flags) than to use something unrelated letter.

File: crates/sncast/src/starknet_commands/call.rs (hunk 1 above)
Comment (franciszekjob) [reply crates/sncast/src/starknet_commands/call.rs:14]: If you refer to `Call` only - it's possible, but I think it's better to maintain consistency and have short option 
 of `contract_address` the same for every command. Then it's not possible as  `c` is already used by `calldata` in `Invoke`.

**Review by cptartur — APPROVED** [review]
