### PR TITLE
Parsing arguments from memory now fail single test only

### LINKED ISSUE #1469: Parsing arguments from memory panics
We should instead fail the test and suggest upgrading the tool/using higher specific version

This was the case especially for the new Cheatcode interface which can be used as a case study

### PR DESCRIPTION
**Pull request by Draggu**
Closes #1469

## Introduced changes

- Parsing arguments from memory now fail single test with message, instead of stoping execution

## Checklist

- [x] Linked relevant issue
- [x] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

### CODE REVIEW

File: crates/cheatnet/tests/cheatcodes/spoof.rs [hunk 1]
```diff
@@ -113,22 +111,24 @@ impl TxInfo {
...
-        let resource_bounds_len = reader.read_felt();
-        let resource_bounds = reader.read_vec_body(
-            3 * resource_bounds_len.to_usize().unwrap(), // ResourceBounds struct has 3 fields
-        );
-        let tip = reader.read_felt();
-        let paymaster_data = reader.read_vec();
-        let nonce_data_availability_mode = reader.read_felt();
-        let fee_data_availability_mode = reader.read_felt();
-        let account_deployment_data = reader.read_vec();
+        let version = reader.read_felt().unwrap();
```
Comment (Arcticae) [inline crates/cheatnet/tests/cheatcodes/spoof.rs:114]: Shouldn't this also return the `Result`? Isn't it possible that the failure will crash the runner here?

**Review by Arcticae — APPROVED** [review]
LGTM, one nitpick

File: crates/cheatnet/tests/cheatcodes/spoof.rs (hunk 1 above)
Comment (piotmag769) [reply crates/cheatnet/tests/cheatcodes/spoof.rs:114]: Why do we unwrap here? Would be nice to leave a comment before resolving

File: crates/cheatnet/src/runtime_extensions/forge_runtime_extension/mod.rs [hunk 2]
```diff
@@ -54,25 +54,26 @@ pub struct ForgeExtension<'a> {
...
             Some(2) => {
                 let contract_addresses: Vec<_> = self
-                    .read_vec()
+                    .read_vec()?
                     .iter()
                     .map(|el| ContractAddress::from_(el.clone()))
                     .collect();
                 CheatTarget::Multiple(contract_addresses)
             }
             _ => unreachable!("Invalid CheatTarget variant"),
```
Comment (piotmag769) [inline crates/cheatnet/src/runtime_extensions/forge_runtime_extension/mod.rs:75]: I know I approved it but I noticed that this can also panic (e.g. if we add additional enum variants and someone doesn't swtich the backend etc.). Can we fix this?

File: crates/cheatnet/tests/cheatcodes/spoof.rs (hunk 1 above)
Comment (Draggu) [reply crates/cheatnet/tests/cheatcodes/spoof.rs:114]: Because it's in our tests only

File: crates/cheatnet/src/runtime_extensions/forge_runtime_extension/mod.rs (hunk 2 above)
Comment (Draggu) [reply crates/cheatnet/src/runtime_extensions/forge_runtime_extension/mod.rs:75]: https://github.com/foundry-rs/starknet-foundry/pull/1880
