### PR TITLE
Restored `super` functionality

### LINKED ISSUE #247: Test compilation bug
A minimal example:
```
src/
├── lib.cairo
└── a.cairo
Scarb.toml
```

`lib.cairo`
```rs
fn func() -> felt252 {
    1
}
```

`a.cairo`
```rs
use pkg::func;

#[test]
fn test() {
    assert(func() == 1, '');
}
```

`Scarb.toml`
```toml
[package]
name = "pkg"
version = "0.1.0"
```

output:
```console
$ snforge
error: Identifier not found.
 --> a.cairo:1:10
use pkg::func;
         ^**^

error: Identifier not found.
 --> a.cairo:1:10
use pkg::func;
         ^**^

[ERROR] Failed to add linked library, for a detailed information, please go through the logs above
```

Funnily enough, if we move the `a.cairo` file outside of src folder, so the structure is like this:
```
src/
└── lib.cairo
a.cairo
Scarb.toml
```

it works
```console
$ snforge
Collected 1 test(s) and 2 test file(s)
Running 1 test(s) from a.cairo
[PASS] a::a::test
Running 0 test(s) from src/lib.cairo
Tests: 1 passed, 0 failed, 0 skipped
```
[pkg.zip](https://github.com/foundry-rs/starknet-foundry/files/12122946/pkg.zip)

### LINKED ISSUE #259: Fix `super` in the test runner.

### PR DESCRIPTION
**Pull request by Radinyn**
Closes #259
Closes #247

### CODE REVIEW

File: starknet-foundry/crates/forge/src/lib.rs [hunk 1]
```diff
@@ -169,15 +179,21 @@ fn collect_tests_from_file(
...
 pub fn run(
-    input_path: &Utf8PathBuf,
+    package_path: &Utf8PathBuf,
+    lib_path: &Utf8PathBuf,
     linked_libraries: &Option<Vec<LinkedLibrary>>,
     runner_config: &RunnerConfig,
     corelib_path: Option<&Utf8PathBuf>,
     contracts: &HashMap<String, StarknetContractArtifacts>,
     predeployed_contracts: &Utf8PathBuf,
 ) -> Result<Vec<TestFileSummary>> {
```
Comment (cptartur) [inline starknet-foundry/crates/forge/src/lib.rs:189]: A this point this method could use some documentation (`/// comment`)

File: starknet-foundry/crates/forge/src/scarb.rs [hunk 2]
```diff
@@ -338,7 +346,7 @@ mod tests {
             .exec()
             .unwrap();
 
-        let (_, _, dependencies, _) =
+        let (_, _, _, dependencies, _) =
```
Comment (cptartur) [inline starknet-foundry/crates/forge/src/scarb.rs:349]: I think we should create an issue to verify if other values than just `dependencies` are set correctly by these methods.

File: starknet-foundry/crates/forge/src/lib.rs [hunk 3]
```diff
@@ -70,25 +70,35 @@ struct TestsFromFile {
...
-    let mut test_files: Vec<Utf8PathBuf> = vec![];
-
-    for entry in WalkDir::new(input_path).sort_by(|a, b| a.file_name().cmp(b.file_name())) {
+fn find_cairo_root_files_in_directory(
+    input_path: &Utf8PathBuf,
+    lib_path: &Utf8PathBuf,
+) -> Result<Vec<Utf8PathBuf>> {
+    let mut test_files: Vec<Utf8PathBuf> = vec![lib_path.clone()];
+    let default_src_path = &input_path.join(Utf8PathBuf::from("/src"));
+    let src_path = lib_path.parent().unwrap_or(default_src_path);
```
Comment (cptartur) [inline starknet-foundry/crates/forge/src/lib.rs:95]: I would just bubble this error if there is no parent instead of using a default value.

File: starknet-foundry/crates/forge/src/lib.rs (hunk 1 above)
Comment (cptartur) [reply starknet-foundry/crates/forge/src/lib.rs:189]: You can create an issue for that.

Comment (Radinyn) [reply starknet-foundry/crates/forge/src/lib.rs:188]: #263

File: starknet-foundry/crates/forge/src/scarb.rs (hunk 2 above)
Comment (Radinyn) [reply starknet-foundry/crates/forge/src/scarb.rs:349]: Done

File: starknet-foundry/crates/forge/src/scarb.rs [hunk 4]
```diff
@@ -338,14 +346,34 @@ mod tests {
...
+            .inherit_stderr()
+            .current_dir(temp.path())
+            .exec()
+            .unwrap();
+
+        let (package_path, lib_path, _, _, _) =
+            dependencies_for_package(&scarb_metadata, &scarb_metadata.workspace.members[0])
+                .unwrap();
+
+        assert!(!package_path.ends_with(Utf8PathBuf::from(".cairo")));
```
Comment (piotmag769) [inline starknet-foundry/crates/forge/src/scarb.rs:372]:
```suggestion
        assert!(package_path.is_dir());
```

File: starknet-foundry/crates/forge/src/scarb.rs [hunk 5]
```diff
@@ -140,14 +146,16 @@ pub fn dependencies_for_package(
...
+
     let corelib = compilation_unit
         .components
         .iter()
         .find(|du| du.source_path.to_string().contains("core/src"))
         .context("corelib could not be found")?;
     let corelib_path = Utf8PathBuf::from(corelib.source_root());
 
-    Ok((base_path, corelib_path, dependencies, target_name))
+    Ok((base_path, lib_path, corelib_path, dependencies, target_name))
```
Comment (piotmag769) [inline starknet-foundry/crates/forge/src/scarb.rs:158]: Would rename `base_path` to `package_path`

File: starknet-foundry/crates/forge/src/main.rs [hunk 6]
```diff
@@ -72,7 +72,7 @@ fn main_execution() -> Result<()> {
     for package in &scarb_metadata.workspace.members {
         let forge_config = forge::scarb::config_from_scarb_for_package(&scarb_metadata, package)?;
 
-        let (base_path, _corelib_path, dependencies, target_name) =
+        let (base_path, lib_path, _corelib_path, dependencies, target_name) =
```
Comment (piotmag769) [inline starknet-foundry/crates/forge/src/main.rs:75]: Would rename `base_path` to `package_path`

File: starknet-foundry/crates/forge/tests/e2e/collection.rs [hunk 7]
```diff
@@ -18,39 +18,27 @@ fn complex_structure() {
...
-        [PASS] fibfabfob::fibfabfob::test_fib
-        [PASS] fibfabfob::fibfabfob::test_fob
-        [PASS] fibfabfob::fibfabfob::test_fab
-        Running 1 test(s) from src/fob/fob_impl.cairo
-        [PASS] fob_impl::fob_impl::test_fob
-        Running 1 test(s) from src/fob.cairo
-        [PASS] fob::fob::test_simple
-        Running 3 test(s) from src/lib.cairo
+        .stdout_matches(indoc! {r#"Collected 16 test(s) and 4 test file(s)
+        Running 12 test(s) from src/lib.cairo
```
Comment (piotmag769) [inline starknet-foundry/crates/forge/tests/e2e/collection.rs:22]: Is it possible to print the package name in this case? This message suggests that all the tests are in the src/lib.cairo

File: starknet-foundry/crates/test-collector/src/lib.rs
Comment (piotmag769) [inline starknet-foundry/crates/test-collector/src/lib.rs:1]: It is just a revert to the version before the fix, right?

Comment (Radinyn) [reply starknet-foundry/crates/test-collector/src/lib.rs:1]: yes

**Review by piotmag769 — APPROVED** [review]

File: starknet-foundry/crates/forge/src/lib.rs [hunk 8]
```diff
@@ -70,27 +70,36 @@ struct TestsFromFile {
...
 }
 
-fn find_cairo_files_in_directory(input_path: &Utf8PathBuf) -> Result<Vec<Utf8PathBuf>> {
-    let mut test_files: Vec<Utf8PathBuf> = vec![];
+fn find_cairo_root_files_in_directory(
+    package_path: &Utf8PathBuf,
+    lib_path: &Utf8PathBuf,
+) -> Result<Vec<Utf8PathBuf>> {
+    let mut test_files: Vec<Utf8PathBuf> = vec![lib_path.clone()];
+    let src_path = lib_path.parent().unwrap();
```
Comment (cptartur) [inline starknet-foundry/crates/forge/src/lib.rs:94]:
```suggestion
    let src_path = lib_path.parent().context("Failed to get parent directory of package")?;
```
Or something like that

File: starknet-foundry/crates/forge/src/scarb.rs [hunk 9]
```diff
@@ -338,14 +352,34 @@ mod tests {
...
+            .exec()
+            .unwrap();
+
+        let (package_path, lib_path, _, _, _) =
+            dependencies_for_package(&scarb_metadata, &scarb_metadata.workspace.members[0])
+                .unwrap();
+
+        assert!(package_path.is_dir());
+        assert!(lib_path.ends_with(Utf8PathBuf::from("src/lib.cairo")));
+        assert!(lib_path.starts_with(package_path));
```
Comment (cptartur) [inline starknet-foundry/crates/forge/src/scarb.rs:380]: 👍

Comment (Radinyn) [reply starknet-foundry/crates/forge/src/scarb.rs:380]: 👍

Comment (piotmag769) [reply starknet-foundry/crates/forge/src/scarb.rs:380]: image

Comment (Radinyn) [reply starknet-foundry/crates/forge/src/scarb.rs:380]: 👍 image

**Review by cptartur — APPROVED** [review]
