### PR TITLE
Use scarb metadata error pretty print

### LINKED ISSUE #1509: Scarb metadata error should be nicely printed
```
+ stdout:
+ {"type":"error","message":"failed to parse manifest at: /private/var/folders/0_/yp337wzx1ss_qgrd9kpfx9_00000gn/T/.tmpqpHqq8/Scarb.toml\n\nCaused by:\n    dependency (snforge_std) specification is ambiguous, only one of `git` or `path` is allowed"}
+ 
```
Currently scarb metadata in forge just redirects json to stdout. if we use json we should interpret and pretty print the error.

### PR DESCRIPTION
**Pull request by Draggu**
Closes #1509

## Introduced changes

- Use `MetadataCommand` output, see: https://github.com/software-mansion/scarb/pull/1098

## Checklist

- [x] Linked relevant issue
- [x] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

### CODE REVIEW

File: crates/scarb-api/src/metadata.rs [hunk 1]
```diff
@@ -6,8 +6,14 @@ pub trait MetadataCommandExt {
...
     fn run(&mut self) -> Result<Metadata, MetadataCommandError> {
-        // logic will go here
-        // keep it now this way to don't rename method calls later
-        self.exec()
+        self.inherit_stdout();
+
+        let result = self.exec();
+
+        if result.is_err() {
+            println!("error: could not gather project metadata from Scarb due to previous error");
```
Comment (Arcticae) [inline crates/scarb-api/src/metadata.rs:14]: This will go into stdout instead of stderr

Comment (Draggu) [reply crates/scarb-api/src/metadata.rs:14]: Yes, as scarb errors go to stdout as well

**Review by Arcticae — APPROVED** [review]
Add the test and we're good to go 🙌
