### PR TITLE
Fix scarb `2.14` scheduled tests

### LINKED ISSUE #3977: Support Scarb 2.14
### Current State

There are failing scheduled tests on 2.14 Scarb

### Objective

Address the failing tests and add support for Scarb 2.14

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MKowalski8**
Closes #3977 

## Introduced changes

- Fix faliing tests:
   - generate new snaps
   - normalize signatures
   - remove (inlined) in 2.14 backtrace

## Checklist

- [x] Linked relevant issue
- [ ] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

### CODE REVIEW

File: crates/cheatnet/src/runtime_extensions/forge_runtime_extension/mod.rs [hunk 1]
```diff
@@ -451,6 +453,8 @@ impl<'a> ExtensionLogic for ForgeExtension<'a> {
                                     )
                                     .unwrap();
 
+                                let signature = signature.normalize_s().unwrap_or(signature);
```
Comment (MKowalski8) [inline crates/cheatnet/src/runtime_extensions/forge_runtime_extension/mod.rs:456]: Note:  `normalize_s()` func follows this [BIP](https://github.com/bitcoin/bips/blob/master/bip-0062.mediawiki#low-s-values-in-signatures)


> #### Low S values in signatures
> 
> The value S in signatures must be between 0x1 and 0x7FFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF 5D576E73 57A4501D DFE92F46 681B20A0 (inclusive). If S is too high, simply replace it by S' = 0xFFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFE BAAEDCE6 AF48A03B BFD25E8C D0364141 - S.

**Comment by MKowalski8** [comment]
obraz

File: crates/forge/tests/e2e/snapshots/main__e2e__gas_report__basic@2.14.0.snap
Comment (cptartur) [inline crates/forge/tests/e2e/snapshots/main__e2e__gas_report__basic@2.14.0.snap:1]: Did you compare these to snapshots for 2.13, if they changed significantly?

Comment (MKowalski8) [reply crates/forge/tests/e2e/snapshots/main__e2e__gas_report__basic@2.14.0.snap:1]: They have not changed at all

Comment (cptartur) [reply crates/forge/tests/e2e/snapshots/main__e2e__gas_report__basic@2.14.0.snap:1]: Great

**Review by cptartur — APPROVED** [review]

**Review by franciszekjob — APPROVED** [review]
