### PR TITLE
Catch network errors while forking

### LINKED ISSUE #791: Forking: ambigious errors when passing incorrect url or being offline
We do not inform that the connection couldn't be established - it is prob bcs in `impl StateReader for ExtendedStateReader` we always return `Ok` even on network errors (we just return `Default`).
Instead we get sth like:

```console
[FAIL] tests::test_forking::hash

Failure data:
    Got an exception while executing a hint:
    Contract not deployed at address: 0x071c8d74edc89330f314f3b1109059d68ebfa68874aa91e9c425a6378ffde00e
```

We should also add tests for cases like:
- [ ] network error
- [ ] invalid URL (parsable, but not pointing to any node)

### PR DESCRIPTION
**Pull request by war-in**
Closes #791

## Introduced changes

- default storage values are not returned when network errors occur

## Checklist

- [x] Linked relevant issue
- [ ] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [ ] Added changes to `CHANGELOG.md`

### CODE REVIEW

**Review by Arcticae — APPROVED** [review]

File: crates/cheatnet/src/state.rs [hunk 1]
```diff
@@ -222,3 +216,13 @@ impl CheatnetState {
...
     }
 }
+
+fn match_node_response<T: Default>(result: StateResult<T>) -> StateResult<T> {
+    match result {
+        Ok(class_hash) => Ok(class_hash),
+        Err(StateError::StateReadError(msg)) if msg.contains("node") => {
+            Err(StateError::StateReadError(msg))
+        }
+        _ => Ok(Default::default()),
```
Comment (piotmag769) [inline crates/cheatnet/src/state.rs:226]: Why do we return default here?

Comment (war-in) [reply crates/cheatnet/src/state.rs:226]: Because we have to

Comment (war-in) [reply crates/cheatnet/src/state.rs:226]: Imagine a situation when someone wants to deploy a new contract when forking.
The state is asked this way:
- dict_state_reader (which does not have a value)
- fork_state_reader:
  - node is fetched and if there is no value, an error is returned
  - we have to return default because blockifier handles the state this way
