### PR TITLE
Fix compiler config validation

### LINKED ISSUE #109: Verify Scarb.toml compiler settings in snforge when launching debugger

### LINKED ISSUE #4254: Config validation for coverage, backtrace and debugger is faulty
1. Doesn't take into account raw `[cairo]` section - only `[profile.{current_profile}.cairo]`.
2. Doesn't take into account new field aliases (without `unstable-` prefixes) - needs Scarb version check to see if this Scarb version provides such aliases.

### LINKED ISSUE #4292: Add tests for cairo config validation fix
Should also cover scarb versions before 2.15.0 
#4290

### PR DESCRIPTION
**Pull request by piotmag769**
Closes #4254
Closes #4292 
Closes https://github.com/software-mansion/cairo-debugger/issues/109

## Introduced changes

- previously the config validation relied on checking the content of the Scarb.toml, which led to poor UX (e.g. `[cairo]` section was ignored completely). Now we read the config from scarb metadata which is more reliable. Also, previously a wrong Scarb.toml was used - the `runtime_manifest` instead of `workspace.manifest_path`

## Checklist

- [x] Linked relevant issue
- [ ] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

### CODE REVIEW

File: crates/forge/src/profile_validation/mod.rs [hunk 1]
```diff
@@ -1,69 +1,59 @@
...
+        check_backtrace_compatibility(test_args, compiler_config, profile)?;
     }
 
     Ok(())
 }
 
-/// Gets the runtime manifest from the [`Metadata`] and parses it into a [`DocumentMut`].
-fn get_manifest(scarb_metadata: &Metadata) -> anyhow::Result<DocumentMut> {
-    Ok(fs::read_to_string(&scarb_metadata.runtime_manifest)?.parse::<DocumentMut>()?)
+fn bool_field_or_unstable(value: &Value, key: &str) -> bool {
```
Comment (piotmag769) [inline crates/forge/src/profile_validation/mod.rs]: This function exists for backwards compability purposes - the keys in config were changed in Scarb [v2.15.0-rc.0](https://github.com/software-mansion/scarb/releases/tag/v2.15.0-rc.0)

File: crates/forge/src/profile_validation/mod.rs [hunk 2]
```diff
@@ -1,69 +1,59 @@
...
 ) -> anyhow::Result<()> {
+    // Config of the first CU is as good as any as all compilation units have the same compiler
+    // config.
+    let Some(compiler_config) = scarb_metadata
+        .compilation_units
+        .first()
+        .map(|cu| &cu.compiler_config)
+    else {
+        return Ok(());
+    };
```
Comment (piotmag769) [inline crates/forge/src/profile_validation/mod.rs:27]: @maciektr idk if it makes sense to check all compilations units - I can do that, but setting different debug info for different targets in the future sounds like a weird edge case that we don't need to cover. WDYT?

Comment (maciektr) [reply crates/forge/src/profile_validation/mod.rs:27]: While this is true, this assumptions relies on underlying Scarb implementation details. Compiler configs are not guaranteed to be identical and this behaviour can change in the future. 
On the other hand, validating against all configs is also not something that I would advice - what you should really do is select targets that you care about (like test targets for test runner) and only validate those. 

If you decide to stick to the first one for now, I am rather okay with that, but it's not my decision to make and please mark it with TODO in such case.

File: crates/forge/src/profile_validation/debugger.rs [hunk 3]
```diff
@@ -1,26 +1,18 @@
...
+    let has_needed_entries = bool_field(compiler_config, "add_functions_debug_info")
+        && bool_field_or_unstable(compiler_config, "add_statements_code_locations_debug_info")
+        && bool_field_or_unstable(compiler_config, "add_statements_functions_debug_info")
+        && str_field(compiler_config, "compiler_optimizations") == "Disabled";
 
     ensure!(
         has_needed_entries,
         formatdoc! {
-            "Scarb.toml must have the following Cairo compiler configuration to launch the debugger:
+            "workspace Scarb.toml must have the following Cairo compiler configuration to launch the debugger:
```
Comment (maciektr) [inline crates/forge/src/profile_validation/debugger.rs]: Nit: showing relative path to the Scarb.toml in users project would be nice here

**Review by maciektr — APPROVED** [review]

File: crates/forge/src/profile_validation/backtrace.rs [hunk 4]
```diff
@@ -27,31 +25,23 @@ fn check_if_native_disabled(test_args: &TestArgs) -> anyhow::Result<()> {
...
-        check_cairo_profile_entries(&manifest, scarb_metadata, BACKTRACE_REQUIRED_ENTRIES);
+        bool_field_or_unstable(compiler_config, "add_statements_code_locations_debug_info")
+            && bool_field_or_unstable(compiler_config, "add_statements_functions_debug_info")
+            && bool_field(compiler_config, "panic_backtrace");
 
     ensure!(
         has_needed_entries,
         formatdoc! {
-            "Scarb.toml must have the following Cairo compiler configuration to run backtrace:
+            "workspace Scarb.toml must have the following Cairo compiler configuration to launch the debugger:
```
Comment (maciektr) [inline crates/forge/src/profile_validation/backtrace.rs]:
```suggestion
            "workspace Scarb.toml must have the following Cairo compiler configuration to run the backtrace:
```

Comment (piotmag769) [reply crates/forge/src/profile_validation/backtrace.rs]: Thx, missed that

File: crates/forge/src/profile_validation/mod.rs (hunk 2 above)
Comment (piotmag769) [reply crates/forge/src/profile_validation/mod.rs]: Changed it to iterate over all relevant targets - please re-review

File: crates/forge/tests/e2e/coverage.rs [hunk 5]
```diff
@@ -33,6 +33,70 @@ fn test_coverage_project_and_pass_args() {
...
+        .arg("--output-path")
+        .arg("./my_file.lcov")
+        .assert()
+        .success();
+
+    assert!(temp.join("my_file.lcov").is_file())
+}
+
+// `skip-optimizations` also sets `inlining-strategy` to `avoid` - available from Scarb 2.15.0
+#[cfg(feature = "run_test_for_scarb_since_2_15_1")]
```
Comment (MKowalski8) [inline crates/forge/tests/e2e/coverage.rs]: I think this feature flag is not needed. In scheduled tests oldest version we run is 2.15.2, so it will never go below 2.15.0. (apply to other places as well). We are also getting rid of this in the near future

File: crates/forge/src/profile_validation/mod.rs [hunk 6]
```diff
@@ -1,69 +1,97 @@
...
     test_args: &TestArgs,
     scarb_metadata: &Metadata,
 ) -> anyhow::Result<()> {
+    let Some(compiler_config) = scarb_metadata
+        .compilation_units
+        .iter()
+        .find(|cu| &cu.target == target)
+        .map(|cu| &cu.compiler_config)
+    else {
+        return Ok(());
```
Comment (MKowalski8) [inline crates/forge/src/profile_validation/mod.rs:53]: Should it just return `Ok(())`?

**Review by MKowalski8 — APPROVED** [review]

File: crates/forge/src/profile_validation/mod.rs (hunk 6 above)
Comment (piotmag769) [reply crates/forge/src/profile_validation/mod.rs:53]: This is just a failsafe - it will never fail anyways. If there exists a target for a package, it has to have a compilation unit corresponding to it

File: crates/forge/tests/e2e/coverage.rs (hunk 5 above)
Comment (piotmag769) [reply crates/forge/tests/e2e/coverage.rs]: I will manually test it with 2.14.0 then to make sure I didn't break backwards compatibility without a reason

File: crates/forge/src/profile_validation/mod.rs (hunk 6 above)
Comment (MKowalski8) [reply crates/forge/src/profile_validation/mod.rs:53]: Could you add this as a comment? It might help someone in the future to understand this. Or even use `unreachable!`here, if you say it will never fail?

File: crates/forge/src/profile_validation/mod.rs [hunk 7]
```diff
@@ -1,69 +1,97 @@
...
-use toml_edit::{DocumentMut, Table};
+/// Checks if the compiler settings provided in [`Metadata`] can be used to run
+/// coverage, backtrace and debugger if applicable.
+pub fn check_compiler_config_compatibility(
+    test_args: &TestArgs,
+    scarb_metadata: &Metadata,
+    packages_to_build: &[PackageMetadata],
+) -> anyhow::Result<()> {
+    for package in packages_to_build {
+        if test_args.no_optimization
```
Comment (maciektr) [inline crates/forge/src/profile_validation/mod.rs:22]: What does this flag represent? 🤔

Comment (piotmag769) [reply crates/forge/src/profile_validation/mod.rs:22]: https://foundry-rs.github.io/starknet-foundry/appendix/snforge/test.html#--no-optimization

Comment (maciektr) [reply crates/forge/src/profile_validation/mod.rs:22]: Ahhh, right

File: crates/forge/src/profile_validation/mod.rs (hunk 6 above)
Comment (piotmag769) [reply crates/forge/src/profile_validation/mod.rs:53]: Added a comment

File: crates/forge/tests/e2e/coverage.rs (hunk 5 above)
Comment (piotmag769) [reply crates/forge/tests/e2e/coverage.rs]: Tested - works with 2.13.0 and 2.14.0

**Review by maciektr — APPROVED** [review]

File: CHANGELOG.md [hunk 8]
```diff
@@ -17,6 +17,11 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 
 - Minimal recommended `Scarb` version is now `2.15.2` (updated from `2.14.0`)
 
+#### Fixed
+
+- Validation of Scarb's compiler config now properly takes into account `[cairo]` section and keys without `unstable-`
+prefix
```
Comment (ddoktorski) [inline CHANGELOG.md]: nit:
```suggestion
- Validation of Scarb's compiler config now properly takes into account `[cairo]` section and keys without `unstable-` prefix
```

**Review by ddoktorski — APPROVED** [review]
