### PR TITLE
Fix `--add-profile` flag

### LINKED ISSUE #2519: Fix `--add-profile` flag
### Which components does the task require to be changed? (think hard pls)

sncast

### Description

When calling 
```shell
sncast \
    account create \ 
    --add-profile profile1
    --url http://127.0.0.1:5050 \
    --name some-name
```

Generated is entry in `snfoundry.toml` with blank `url` field

```
[sncast.profile1]
account = "some-name"
accounts-file = "/path/to/starknet_open_zeppelin_accounts.json"
url = ""
```

### PR DESCRIPTION
**Pull request by kkawula**
Closes #2519

## Introduced changes

- Flag fixed

## Checklist

- [x] Linked relevant issue
- [x] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

### CODE REVIEW

File: crates/sncast/src/starknet_commands/account/add.rs [hunk 1]
```diff
@@ -22,7 +22,7 @@ pub struct Add {
     pub name: String,
 
     /// Address of the account
-    #[clap(short, long, requires = "private_key_input")]
```
Comment (kkawula) [inline crates/sncast/src/starknet_commands/account/add.rs:25]: Command add: Short option names must be unique for each argument, but '-a' is in use by both 'address' and 'account'

**Review by cptartur — APPROVED** [review]

File: crates/sncast/src/starknet_commands/account/add.rs (hunk 1 above)
Comment (kkawula) [reply crates/sncast/src/starknet_commands/account/add.rs:25]: Reverted bcs of global config future rework
