### PR TITLE
Cache default value after failed request in `ForkStateReader`

### LINKED ISSUE #2849: Fork caching bug

### PR DESCRIPTION
**Pull request by franciszekjob**
Closes #2849

## Introduced changes

Update the logic of `ForkStateReader` - if we receive `StarknetError::ContractNotFound`, we additionaly cache such request.

## Checklist

- [x] Linked relevant issue
- [x] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

### CODE REVIEW

**Review by cptartur — APPROVED** [review]

File: crates/cheatnet/src/forking/state.rs [hunk 1]
```diff
@@ -134,7 +134,14 @@ impl StateReader for ForkStateReader {
                 Ok(value_sf)
             }
             Err(ProviderError::Other(boxed)) => other_provider_error(boxed),
-            Err(ProviderError::StarknetError(StarknetError::ContractNotFound)) => Ok(Default::default()),
+            Err(ProviderError::StarknetError(StarknetError::ContractNotFound)) => {
+                self.cache.borrow_mut().cache_get_storage_at(
+                    contract_address,
+                    key,
+                    Default::default(),
```
Comment (ddoktorski) [inline crates/cheatnet/src/forking/state.rs:141]: nit:
```suggestion
                    Felt::default(),
```

File: crates/cheatnet/src/forking/state.rs [hunk 2]
```diff
@@ -134,7 +134,14 @@ impl StateReader for ForkStateReader {
...
+                );
+                Ok(Default::default())
```
Comment (ddoktorski) [inline crates/cheatnet/src/forking/state.rs:143]: nit:
```suggestion
                Ok(Felt::default())
```
Also in the other functions

**Review by ddoktorski — APPROVED** [review]

**Review by piotmag769 — APPROVED** [review]
