### PR TITLE
CallFailure::Panic for unknown entry point

### LINKED ISSUE #1739: Unknown Entry Point Error fails `should_panic` tests
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

https://github.com/foundry-rs/starknet-foundry/blob/dc55ebf4f20de60e7d743d24286174e013328033/crates/cheatnet/src/runtime_extensions/call_to_blockifier_runtime_extension/rpc.rs#L147

### PR DESCRIPTION
**Pull request by drknzz**
Closes #1739

## Introduced changes

- [Change CallFailure::Error to CallFailure::Panic](https://github.com/foundry-rs/starknet-foundry/commit/4cef7f838992f41804e4f8e79a2787e3f4816a67)

## Checklist

- [x] Linked relevant issue
- [x] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

### CODE REVIEW

File: crates/forge/tests/integration/should_panic.rs [hunk 1]
```diff
@@ -35,3 +38,43 @@ fn should_panic() {
...
+        indoc!(
+            r"
+            use array::ArrayTrait;
+            use starknet::{call_contract_syscall, ContractAddress, Felt252TryIntoContractAddress};
+            use result::ResultTrait;
+
+            use snforge_std::{declare, ContractClass, ContractClassTrait};
+
+            #[test]
+            #[should_panic]
```
Comment (drknzz) [inline crates/forge/tests/integration/should_panic.rs:54]: In rust, it's possible to have `should_panic` match expected error by a substring, meanwhile we [always assert the full message](https://github.com/foundry-rs/starknet-foundry/blob/07c3ef85a97bfb1ed8eacaa529f6e98569489f94/crates/forge-runner/src/test_case_summary.rs#L251). Maybe it's something we could add an option for?

Comment (drknzz) [reply crates/forge/tests/integration/should_panic.rs:54]: Here the string error cannot be asserted because it contains the address of a contract

**Review by piotmag769 — APPROVED** [review]

File: crates/forge/tests/integration/should_panic.rs (hunk 1 above)
Comment (piotmag769) [reply crates/forge/tests/integration/should_panic.rs:54]: We can add an issue for that, good idea. I think substring should be the default behavior
