### PR TITLE
Fix required tools validation

### LINKED ISSUE #2947: Do not always require Rust in compatibility check
### Current State

Currently, we always check if USC, Scarb and Rust are installed when running forge.
Rust is no longer needed if using scarb supporting prebuilt packages in registry.

### Objective

Revamp rust checking logic

### Additional Context

If user is on the Scarb version that supports prebuilt packages we shouldn't require Rust to be installed.

One concern is that if user doesn't opt-in into prebuilt packages, then Rust will be required even on Scarb versions that support them - this should be handled somehow.

### PR DESCRIPTION
**Pull request by ddoktorski**
## Introduced changes

- Run `check_requirements` only for `snforge test` command
- Require Rust installed only for Scarb `<2.10.0`

### CODE REVIEW

**Review by kkawula — APPROVED** [review]

File: crates/forge/src/lib.rs [hunk 1]
```diff
@@ -302,5 +291,29 @@ fn check_requirements(output_on_success: bool) -> Result<()> {
             r"universal-sierra-compiler (?<version>[0-9]+.[0-9]+.[0-9]+)",
         ),
     });
-    requirements_checker.check()
+    requirements_checker.check()?;
+
+    let scarb_version = ScarbCommand::version().run()?.scarb;
+    if scarb_version <= MINIMAL_SCARB_VERSION_PREBUILT_PLUGIN {
```
Comment (franciszekjob) [inline crates/forge/src/lib.rs:297]: Shouldn't that be `<`?
```suggestion
    if scarb_version < MINIMAL_SCARB_VERSION_PREBUILT_PLUGIN {
```

Comment (ddoktorski) [reply crates/forge/src/lib.rs:297]: Yes absolutely

**Review by franciszekjob — APPROVED** [review]

File: crates/forge/src/lib.rs [hunk 2]
```diff
@@ -302,5 +291,29 @@ fn check_requirements(output_on_success: bool) -> Result<()> {
...
+                r"rustc (?<version>[0-9]+.[0-9]+.[0-9]+)",
+            ),
+            helper_text: "Follow instructions from https://www.rust-lang.org/tools/install"
+                .to_string(),
+        });
+
+        requirements_checker.check()?;
+    }
+
+    Ok(())
```
Comment (cptartur) [inline crates/forge/src/lib.rs:318]: Can't we only conditionally add the rust requirement, but run `requirements_checker.check()?;` only once?

Comment (ddoktorski) [reply crates/forge/src/lib.rs:318]: It seems more accurate to first check if `Scarb` is installed and then check the version, otherwise the command will fail when executing `ScarbCommand::version().run()?`. Tbh I just realized that we don't print a formatted message when a given tool is not installed, instead we return an error. I think we should change this, but maybe not in this PR.

Comment (cptartur) [reply crates/forge/src/lib.rs:318]: Right, didn't catch that.

> Tbh I just realized that we don't print a formatted message when a given tool is not installed, instead we return an error. I think we should change this, but maybe not in this PR.

Correct, this needs to be addressed. I've created #2807 sometime ago.

**Review by cptartur — APPROVED** [review]
