### PR TITLE
Fix live printing

### LINKED ISSUE #843: Investigate using `FuturesUnordered` in `run_tests_from_crate`
Related discussion: https://github.com/foundry-rs/starknet-foundry/pull/775/files/28fdce3402381a383fc31886b36a4715dbd80d18#r1349983675

### LINKED ISSUE #860: Fix live printing
Right now, tests results are printed after execution of all tests finishes. They should be printed as they are processed.

### PR DESCRIPTION
**Pull request by cptartur**
Closes #860 
Closes #843 

## Introduced changes

- Test from different crates no longer run in parallel
- Tests from crate are now run unordered.
- Outputs from these tests are printed immediately after test case execution completed
- Added new macro for testing e2e tests outputs that does not depend on test order. This macro is limited right now in that it asserts the output line by line. This is problematic for outputs that are longer than one line, like the whole output of `[FAIL]` test. This will be extended in future PRs.

## Checklist

- [x] Linked relevant issue
- [x] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

### CODE REVIEW

File: crates/forge/tests/e2e/common/runner.rs [hunk 1]
```diff
@@ -205,3 +205,47 @@ pub(crate) fn get_current_branch() -> String {
...
+macro_rules! assert_stdout_contains {
+    ( $output:expr, $lines:expr ) => {{
+        use regex::Regex;
+
+        let output = $output.get_output();
+        let stdout = String::from_utf8(output.stdout.clone()).unwrap();
+
+        for line in $lines.lines() {
+            let escaped = regex::escape(line);
+            let replaced = escaped.replace("\\[\\.\\.\\]", ".*");
```
Comment (piotmag769) [inline crates/forge/tests/e2e/common/runner.rs:219]: Smart

**Review by piotmag769 — APPROVED** [review]

File: crates/forge/tests/e2e/common/runner.rs [hunk 2]
```diff
@@ -205,3 +207,85 @@ pub(crate) fn get_current_branch() -> String {
...
+        if let Some(index) = index {
+            result.push((element.clone(), index));
+        }
+    }
+
+    result
+}
+
+pub(crate) fn is_present(line: &str, actual: &mut Vec<String>, asserted: &Vec<String>) -> bool {
+    let present = intersection_with_wildcard(asserted, actual);
```
Comment (piotmag769) [inline crates/forge/tests/e2e/common/runner.rs:233]: Why do we need to search for the whole pattern instead of just `line`? I think it would simplify the flow by a lot

**Review by piotmag769 — CHANGES_REQUESTED** [review]

File: crates/forge/tests/e2e/common/runner.rs [hunk 3]
```diff
@@ -205,3 +207,85 @@ pub(crate) fn get_current_branch() -> String {
...
+
+pub(crate) fn intersection_with_wildcard(
+    asserted: &Vec<String>,
+    actual: &Vec<String>,
+) -> Vec<(String, usize)> {
+    let mut result = vec![];
+
+    for element in asserted {
+        let escaped = regex::escape(element);
+        let replaced = escaped.replace("\\[\\.\\.\\]", ".*");
```
Comment (tkumor3) [inline crates/forge/tests/e2e/common/runner.rs:219]: Doesn't it change the behavior of [..]? [..] is limited to one line, `.*` is not

**Review by tkumor3 — APPROVED** [review]

File: CHANGELOG.md [hunk 4]
```diff
@@ -12,6 +12,12 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 #### Changed
 
 - `snforge_std::PrintTrait` will not convert values representing ASCII control characters to strings
+- Test from different crates are no longer run in parallel
+- Test outputs are printed in non-deterministic order
```
[the remark this answers is not in the document]
Comment (cptartur) [reply CHANGELOG.md:16]: It's an important change that was introduced, it needs to be mentioned in the changelog.

File: crates/forge/tests/e2e/common/runner.rs (hunk 3 above)
Comment (cptartur) [reply crates/forge/tests/e2e/common/runner.rs]: We are matching the output line by line, so it shouldn't be a problem.
