### PR TITLE
Validate forge packages

### LINKED ISSUE #2975: Run `scarb lint` on forge packages
### Current State

Currently, we do not lint our packages at all

### Objective

Run `scarb lint` on forge packages

### Additional Context

Setup a CI workflow that will lint packages, including `forge new` templates. Additionally, fix the already broken lints.

### LINKED ISSUE #2976: Check template for build warnings
### Current State

Currently, I don't think we check for build warnings.
If we do, please close the issue.

### Objective

Validate if snforge template does not produce build warnings

### Additional Context

Probably can be resolved by running `scarb check` on it and validating the output doesn't contain errors.

It seems it can also be resolved by adding:
```
[cairo]
allow-warnings = false
```
to `Scarb.toml`.

### PR DESCRIPTION
**Pull request by franciszekjob**
Closes #2975
Closes #2976

## Introduced changes

- Validate `snforge_std` and `sncast_std` templates
- Validate (`scarb check` and `scarb lint`) on forge templates

## Checklist

- [x] Linked relevant issue
- [x] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

### CODE REVIEW

File: crates/forge/tests/integration/gas.rs
Comment (franciszekjob) [inline crates/forge/tests/integration/gas.rs:1]: note: Gas has changed because we're using `!=` instead of `<` comparison.

File: .github/workflows/ci.yml [hunk 1]
```diff
@@ -267,22 +267,29 @@ jobs:
...
-          exit 0
+          chmod +x ./scripts/setup_snforge_templates.sh
+          ./scripts/setup_snforge_templates.sh
+      - name: Check packages formatting
+        run: ./scripts/scarb_fmt.sh
+      - uses: software-mansion/setup-scarb@v1
+        with:
+          scarb-version: "2.10.0"
+      - name: Check packages linting
+        run: ./scripts/scarb_lint.sh
```
Comment (franciszekjob) [inline .github/workflows/ci.yml:292]: note: `scarb lint` is available from 2.10.0, hence need to use different scarb version

File: crates/forge/tests/integration/gas.rs [hunk 2]
```diff
@@ -1201,15 +1201,15 @@ fn contract_keccak_cost_sierra_gas() {
...
+    // 1157519 = reported consumed sierra gas
+    // 0 l1_gas + 96 l1_data_gas + (142810 + 50000 + 87650 + 1157519) l2 gas
     assert_gas(
         &result,
         "contract_keccak_cost",
         GasVector {
             l1_gas: GasAmount(0),
             l1_data_gas: GasAmount(96),
-            l2_gas: GasAmount(1_439_395),
+            l2_gas: GasAmount(1_438_075),
```
Comment (franciszekjob) [inline crates/forge/tests/integration/gas.rs:1212]: note: Gas changes are because of modifications in gas checker contract - now we're using `!=` instead of `<` in loops.

File: scripts/scarb_lint.sh
Comment (ddoktorski) [inline scripts/scarb_lint.sh:1]: Tbh do we need checking lint in test packages at all? What are the benefits of this?

Comment (franciszekjob) [reply scripts/scarb_lint.sh:1]: It's a tiny improvement of devex. It's not a big effort so imo we should leave it.

Comment (ddoktorski) [reply scripts/scarb_lint.sh:1]: I must disagree. It seems like quite a lot of effort to maintain this compared to the value it brings, and it also makes our already fat CI even bigger.

File: .github/workflows/ci.yml [hunk 3]
```diff
@@ -267,22 +267,29 @@ jobs:
...
-          output=$(find . -type f -name "Scarb.toml" -execdir sh -c '
-              echo "Running \"scarb fmt\" in directory: $PWD"
-              scarb fmt --check
-          ' \;)
-          echo "$output"
-          if grep -iq "Diff" <<< "$output"; then
-              exit 1
-          fi
-          exit 0
+          chmod +x ./scripts/setup_snforge_templates.sh
```
[the remark this answers is not in the document]
Comment (franciszekjob) [reply .github/workflows/ci.yml]: good catch 👍

File: scripts/setup_snforge_templates.sh
[the remark this answers is not in the document]
Comment (franciszekjob) [reply scripts/setup_snforge_templates.sh:1]: No, assuming that packages are correctly lined and can be compiled.

File: scripts/scarb_lint.sh [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+' \;)
+
+echo "$output"
+
+# Check for lint warnings, we need to do it this way because `scarb lint` returns 0 even if there are warnings
+if grep -iq "warning: Plugin diagnostic:" <<< "$output"; then
+    exit 1
+# Check for missing `edition`` field
+elif grep -iq "warn: `edition` field not set in `[package]` section for package" <<< "$output"; then
+    exit 1
```
Comment (kkawula) [inline scripts/scarb_lint.sh:40]: Maybe it is worth creating an issue for that. If in the future, `scarb lint` can change warning into an error

**Review by kkawula — CHANGES_REQUESTED** [review]

File: CHANGELOG.md [hunk 5]
```diff
@@ -12,6 +12,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 #### Added
 
 - `--template` flag to `snforge new` command that allows selecting a template for the new project. Possible values are `balance-contract` (default), `cairo-program` and `erc20-contract`
+- `Scarb.toml` created by the `snforge new` command now includes the entry `allow-warnings = false` for Cairo checks
```
[the remark this answers is not in the document]
Comment (franciszekjob) [reply CHANGELOG.md:15]: Fine, it may be too impactful. removing.

File: scripts/scarb_lint.sh (hunk 4 above)
Comment (franciszekjob) [reply scripts/scarb_lint.sh]: #3148

**Comment by franciszekjob** [comment]
@ddoktorski @kkawula
I've removed lint-related changes with internal packages and moved the tests from CI to e2e (as discussed with @ddoktorski ). Take a look

File: .github/workflows/ci.yml [hunk 6]
```diff
@@ -267,23 +270,6 @@ jobs:
       - uses: software-mansion/setup-universal-sierra-compiler@v1
       - run: cargo test --release -p scarb-api
 
-  scarbfmt:
```
Comment (cptartur) [inline .github/workflows/ci.yml:270]: Any reason we no longer do this?

File: .github/workflows/ci.yml [hunk 7]
```diff
@@ -320,6 +306,8 @@ jobs:
       - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab
       - uses: actions/checkout@v4
       - uses: software-mansion/setup-scarb@v1
+        with:
+          scarb-version: "2.10.0"
```
Comment (cptartur) [inline .github/workflows/ci.yml:310]: Why are we using a fixed scarb version here? 
Also I guess we should eventually remove this, an issue for this would be good.

File: crates/forge/tests/e2e/packages_validation.rs [hunk 8]
```diff
@@ -0,0 +1,149 @@
...
+        let path = path.unwrap().path();
+        if path.is_dir() {
+            matches.append(&mut find_files_recursively(
+                Utf8PathBuf::from(path.to_string_lossy().to_string()),
+                file_name,
+            ));
+        } else if path.to_string_lossy().contains(file_name) {
+            matches.push(Utf8PathBuf::from(path.to_string_lossy().to_string()));
+        }
+    }
```
Comment (cptartur) [inline crates/forge/tests/e2e/packages_validation.rs:26]: I think we could use walkdir for this, no? https://docs.rs/walkdir/latest/walkdir/

File: crates/forge/tests/e2e/packages_validation.rs [hunk 9]
```diff
@@ -0,0 +1,149 @@
+use std::{fs, process::Stdio};
+
+use super::common::runner::runner;
+use assert_fs::prelude::PathChild;
+use camino::Utf8PathBuf;
+use clap::ValueEnum;
+use forge::Template;
+use project_root::get_project_root;
```
Comment (cptartur) [inline crates/forge/tests/e2e/packages_validation.rs:8]: This package is just a single function with a couple of lines, maybe we could just implement it ourselves?

File: crates/forge/tests/e2e/packages_validation.rs [hunk 10]
```diff
@@ -0,0 +1,149 @@
...
+            .success();
+
+        let package_path = temp_dir.child(package_name);
+        let package_path = Utf8PathBuf::from_path_buf(package_path.to_path_buf())
+            .expect("Failed to convert to Utf8PathBuf");
+
+        // Overwrite Scarb.toml with `allow-warnings = true`
+        let scarb_toml_path = package_path.join("Scarb.toml");
+        let mut scarb_toml = fs::read_to_string(&scarb_toml_path).unwrap();
+        scarb_toml.push_str("\n[cairo]\nallow-warnings = true\n");
```
Comment (cptartur) [inline crates/forge/tests/e2e/packages_validation.rs:129]: Why do we allow them?

File: crates/forge/tests/e2e/packages_validation.rs [hunk 11]
```diff
@@ -0,0 +1,149 @@
...
+        fs::write(&scarb_toml_path, &scarb_toml).expect("Failed to write to Scarb.toml");
+
+        check_and_lint(package_path);
+    }
+}
+
+#[test_case("snforge_std")]
+#[test_case("sncast_std")]
```
Comment (cptartur) [inline crates/forge/tests/e2e/packages_validation.rs:137]: This validates sncast_std even though it is in `forge` crate. I think it'd make more sense in a separate crate that checks both of these crates (and we could expand it to other crates easily in the future if needed).

**Review by cptartur — CHANGES_REQUESTED** [review]

File: .github/workflows/ci.yml (hunk 6 above)
Comment (franciszekjob) [reply .github/workflows/ci.yml:270]: We do it in e2e test

File: .github/workflows/ci.yml (hunk 7 above)
Comment (franciszekjob) [reply .github/workflows/ci.yml:310]: Not needed, it was needed because of some linting changes (which aren't present anymore). Removed.

File: crates/forge/tests/e2e/packages_validation.rs (hunk 9 above)
Comment (franciszekjob) [reply crates/forge/tests/e2e/packages_validation.rs:8]: We can but don't wan to mix changes in this PR, can be addressed in separate one.

File: crates/forge/tests/e2e/packages_validation.rs (hunk 10 above)
Comment (franciszekjob) [reply crates/forge/tests/e2e/packages_validation.rs:129]: We do this only to ensure that scarb check will fail if there are any warnings (that's even suggested in issue description + we've talked about it offline yesterday 😅 ) . Note that we do it only for test packages, we don't include it in `Scarb.toml` template.

File: crates/forge/tests/e2e/packages_validation.rs (hunk 11 above)
Comment (franciszekjob) [reply crates/forge/tests/e2e/packages_validation.rs:137]: Good catch, will move it.

File: crates/forge/tests/e2e/packages_validation.rs (hunk 10 above)
Comment (cptartur) [reply crates/forge/tests/e2e/packages_validation.rs:122]: But shouldn't it be `allow_warnings=false` then?

Comment (franciszekjob) [reply crates/forge/tests/e2e/packages_validation.rs:122]: Oops, should be, it was a typo.

File: .github/workflows/ci.yml [hunk 12]
```diff
@@ -140,6 +140,8 @@ jobs:
       - uses: software-mansion/setup-universal-sierra-compiler@v1
 
       - run: cargo test --package forge --features scarb_since_2_10 sierra_gas
+      - run: cargo test --package forge --features scarb_since_2_10 validate_templates
+      - run: cargo test --package packages_validation --features scarb_since_2_10 validate_cairo_libs
```
Comment (ddoktorski) [inline .github/workflows/ci.yml:144]: It would be better to extend `scarbfmt` job and add these steps there. It could be renamed to something like `scarb fmt and lint`

File: crates/forge/tests/e2e/templates_validation.rs [hunk 13]
```diff
@@ -0,0 +1,41 @@
...
+use forge::Template;
+use packages_validation::check_and_lint;
+
+#[test]
+fn validate_templates() {
+    let temp_dir = assert_fs::TempDir::new().expect("Unable to create a temporary directory");
+
+    let templates = Template::value_variants();
+
+    for template in templates {
```
Comment (ddoktorski) [inline crates/forge/tests/e2e/templates_validation.rs:16]: nit: Why not to use `#[test_case]` instead for each template?

Comment (franciszekjob) [reply crates/forge/tests/e2e/templates_validation.rs:16]: To prevent from forgetting about adding test case when new template is added.

File: .github/workflows/ci.yml (hunk 12 above)
Comment (franciszekjob) [reply .github/workflows/ci.yml:144]: What's the rationale? Packages validation tests are run twice - normally in e2e suite and here with scarb 2.10.
I don't think we should spread tests run with `scarb_since_2_10` feature flag across many jobs.
Once our minimal supported scarb version is 2.10, then we will just remove this job and there won't be need to modify others.

Comment (franciszekjob) [reply .github/workflows/ci.yml:144]: > That's true in the case of validate_templates, but what about the packages_validation tests?

Right, it should be added to run without feature flag, now I see your point.

File: scripts/scarbfmt.sh [hunk 14]
```diff
@@ -1,12 +1,10 @@
...
-
-popd || exit
+output=$(find . -type f -name "Scarb.toml" -execdir sh -c '
+    echo "Running \"scarb fmt --check\" in directory: $PWD"
+    scarb fmt --check
+' \;)
+echo "$output"
+if grep -iq "Diff" <<< "$output"; then
+    exit 1
+fi
```
Comment (kkawula) [inline scripts/scarbfmt.sh:10]: nit. bash generally uses 2 spaces for indentation
you can easily format code with `shfmt -i 2 <file>`
```suggestion
output=$(find . -type f -name "Scarb.toml" -execdir sh -c '
    echo "Running \"scarb fmt --check\" in directory: $PWD"
    scarb fmt --check
' \;)
echo "$output"
if grep -iq "Diff" <<<"$output"; then
  exit 1
fi
```

File: crates/packages_validation/Cargo.toml [hunk 15]
```diff
@@ -0,0 +1,15 @@
+[package]
+name = "packages_validation"
+version = "1.0.0"
+edition.workspace = true
```
[the remark this answers is not in the document]
Comment (ddoktorski) [reply crates/packages_validation/Cargo.toml:4]: Sounds good to me

**Comment by cptartur** [comment]
@franciszekjob please re-request when it's ready for another review (xtask is implemented?)

File: crates/packages_validation/Cargo.toml (hunk 15 above)
[the remark this answers is not in the document]
Comment (franciszekjob) [reply crates/packages_validation/Cargo.toml:4]: as dicsussed offline: xtask seems good, but in order to validate templates we're using enum from forge, also the `check_and_lint` function is used both in libs and templates validation. Let's leave it in crate.

File: crates/packages_validation/Cargo.toml [hunk 16]
```diff
@@ -0,0 +1,15 @@
+[package]
+name = "packages_validation"
```
Comment (kkawula) [inline crates/packages_validation/Cargo.toml:2]: Maybe it should be renamed? 
sth like `testing_packages_validatoin`, in order to distinguish this package from others

File: crates/packages_validation/src/lib.rs [hunk 17]
```diff
@@ -0,0 +1,37 @@
+use camino::Utf8PathBuf;
+use scarb_api::ScarbCommand;
+use std::process::Stdio;
+
+pub fn check_and_lint(package_path: Utf8PathBuf) {
+    println!("Running `scarb check` in directory {package_path}");
```
[the remark this answers is not in the document]
Comment (franciszekjob) [reply crates/packages_validation/src/lib.rs:6]: Without this we won't know for which package `scarb check` has failed - it's not cluttering.
We do the same for docs validation btw.

File: scripts/scarbfmt.sh
[the remark this answers is not in the document]
Comment (franciszekjob) [reply scripts/scarbfmt.sh:1]: In fact, it's in separate script 😅 . Am I missing something?

File: crates/packages_validation/Cargo.toml (hunk 16 above)
Comment (franciszekjob) [reply crates/packages_validation/Cargo.toml:2]: I think current name already distinguishes it from others, but I'm open for change. Wdyt @ddoktorski @cptartur ?

File: crates/packages_validation/src/lib.rs [hunk 18]
```diff
@@ -0,0 +1,37 @@
...
+        .arg("check")
+        .command()
+        .stdout(Stdio::inherit())
+        .stderr(Stdio::inherit())
+        .output()
+        .expect("Failed to run `scarb check`");
+    assert!(check_output.status.success(), "`scarb check` failed");
+
+    // TODO(#3149)
+    if cfg!(feature = "scarb_since_2_10") {
```
[the remark this answers is not in the document]
Comment (franciszekjob) [reply crates/packages_validation/src/lib.rs:18]: Could you clarify a bit? We run `scarb lint` only for scarb 2.10.0 (because it provides lint).

[the remark this answers is not in the document]
Comment (franciszekjob) [reply crates/packages_validation/src/lib.rs:18]: discussed offline, it's fine as it is now

File: crates/packages_validation/Cargo.toml (hunk 16 above)
Comment (cptartur) [reply crates/packages_validation/Cargo.toml:2]: Does rust workspace structure allow for nesting? If so, maybe it'd make sense to have a `crates/testing` directory? Then we wouldn't need to include `testing_` in the crate name.

We could possible move code from shared::test_utils there as well.

**Comment by cptartur** [comment]
@franciszekjob please re-request review after outstanding comments have been answered (or addressed) 🙏

File: scripts/scarbfmt.sh
[the remark this answers is not in the document]
Comment (franciszekjob) [reply scripts/scarbfmt.sh:1]: Restored.

File: crates/packages_validation/Cargo.toml (hunk 16 above)
Comment (franciszekjob) [reply crates/packages_validation/Cargo.toml]: I've added new crates `testing` and `packages_validation` inside. 

> We could possible move code from shared::test_utils there as well.

Will see it that makes sense and potentially move it in separate PR 👍

File: crates/packages_validation/tests/cairo_libs.rs
[the remark this answers is not in the document]
Comment (franciszekjob) [reply crates/packages_validation/tests/cairo_libs.rs:1]: Moved

File: .github/workflows/ci.yml [hunk 19]
```diff
@@ -276,6 +284,12 @@ jobs:
       - uses: software-mansion/setup-universal-sierra-compiler@v1
       - name: Run tests
         run: cargo test --release -p sncast
+      # TODO(#3096): Remove running tests with `scarb_since_2_10`
+      - uses: software-mansion/setup-scarb@v1
+        with:
+          scarb-version: "2.10.1"
```
[the remark this answers is not in the document]
Comment (franciszekjob) [reply .github/workflows/ci.yml:290]: But we need to set specific version of scarb here, in this case 2.10.1, that's why we use it again.

File: .github/workflows/ci.yml [hunk 20]
```diff
@@ -44,6 +44,14 @@ jobs:
       - uses: software-mansion/setup-scarb@v1
       - uses: software-mansion/setup-universal-sierra-compiler@v1
       - run: cargo test --release --lib -p forge
+      # TODO(#3096): Remove running tests with `scarb_since_2_10`
+      - uses: software-mansion/setup-scarb@v1
+        with:
+          scarb-version: "2.10.1"
```
[the remark this answers is not in the document]
Comment (franciszekjob) [reply .github/workflows/ci.yml:50]: Reply same as above.

File: .github/workflows/ci.yml (hunk 19 above)
[the remark this answers is not in the document]
Comment (kkawula) [reply .github/workflows/ci.yml:290]: We probably can removed one of these

File: crates/forge/tests/e2e/templates.rs [hunk 21]
```diff
@@ -0,0 +1,38 @@
...
+
+    let package_path = temp_dir.child(package_name);
+    let package_path = Utf8PathBuf::from_path_buf(package_path.to_path_buf())
+        .expect("Failed to convert to Utf8PathBuf");
+
+    // Overwrite Scarb.toml with `allow-warnings = false`
+    let scarb_toml_path = package_path.join("Scarb.toml");
+    let mut scarb_toml = fs::read_to_string(&scarb_toml_path).unwrap();
+    scarb_toml.push_str("\n[cairo]\nallow-warnings = false\n");
+    fs::write(&scarb_toml_path, &scarb_toml).expect("Failed to write to Scarb.toml");
```
Comment (kkawula) [inline crates/forge/tests/e2e/templates.rs:35]: Maybe to avoid bugs in the future, we should use `toml_edit` crate to add this entry without creating conflicts?

File: Cargo.toml [hunk 22]
```diff
@@ -14,7 +14,9 @@ members = [
     "crates/configuration",
     "crates/universal-sierra-compiler-api",
     "crates/docs",
-    "crates/debugging"
+    "crates/debugging",
+    "crates/testing",
+    "crates/testing/packages_validation",
```
Comment (cptartur) [inline Cargo.toml:19]: Can't we do something along the lines of this?

```suggestion
    "crates/testing/*"
```

File: crates/testing/Cargo.toml
Comment (cptartur) [inline crates/testing/Cargo.toml:1]: I don't think we need an empty `testing` package (unless there is now way around it). It should just be a plain directory containing testing related crates.

File: crates/testing/packages_validation/src/lib.rs [hunk 23]
```diff
@@ -0,0 +1,54 @@
...
+        .expect("Failed to get project root")
+        .join(package_name);
+    let package_path = package_path
+        .canonicalize()
+        .expect("Failed to canonicalize path");
+    let package_path =
+        Utf8PathBuf::from_path_buf(package_path).expect("Failed to convert to Utf8PathBuf");
+
+    check_and_lint(&package_path);
+}
```
Comment (cptartur) [inline crates/testing/packages_validation/src/lib.rs:54]: Not sure if resolving paths to packages should be responsibility of this package - it makes it less flexible. Why not provide paths at the caller site? 

The paths when running `cargo test` have a stable working directory, so we can just hardcode them at caller site https://doc.rust-lang.org/cargo/commands/cargo-test.html#working-directory-of-tests

File: crates/forge/tests/e2e/templates.rs [hunk 24]
```diff
@@ -0,0 +1,38 @@
...
+            "--template",
+            template.to_string().as_str(),
+            &package_name,
+        ])
+        .assert()
+        .success();
+
+    let package_path = temp_dir.child(package_name);
+    let package_path = Utf8PathBuf::from_path_buf(package_path.to_path_buf())
+        .expect("Failed to convert to Utf8PathBuf");
```
Comment (cptartur) [inline crates/forge/tests/e2e/templates.rs:29]: We can probably hardcode these, see my comment about paths below

File: crates/forge/tests/e2e/templates.rs (hunk 21 above)
Comment (cptartur) [reply crates/forge/tests/e2e/templates.rs:35]: +1 for `toml_edit`, we already use it in some places.

**Review by cptartur — CHANGES_REQUESTED** [review]

File: .github/workflows/ci.yml (hunk 19 above)
[the remark this answers is not in the document]
Comment (franciszekjob) [reply .github/workflows/ci.yml:290]: No, because then we will use version from `.tool-versions` file, which ATM is 2.9.4.
Once minimal supported is 2.10, then we can remove this step (as mentioned in the comment).

File: crates/forge/tests/e2e/templates.rs (hunk 21 above)
Comment (franciszekjob) [reply crates/forge/tests/e2e/templates.rs:35]: Applied

File: Cargo.toml (hunk 22 above)
Comment (franciszekjob) [reply Cargo.toml:19]: I don't think so. Note that above we do the same:

https://github.com/foundry-rs/starknet-foundry/blob/master/Cargo.toml#L9-L10

File: crates/testing/packages_validation/src/lib.rs (hunk 23 above)
Comment (franciszekjob) [reply crates/testing/packages_validation/src/lib.rs:54]: > Not sure if resolving paths to packages should be responsibility of this package - it makes it less flexible. Why not provide paths at the caller site?

Valid point, applied

File: crates/forge/tests/e2e/templates.rs (hunk 24 above)
Comment (franciszekjob) [reply crates/forge/tests/e2e/templates.rs:29]: In this case w we shouldn't hardcode them - note that these the package name is dynamic, depending on specific test case.

File: crates/forge/tests/code_quality.rs [hunk 25]
```diff
@@ -0,0 +1,18 @@
+use camino::Utf8PathBuf;
+use packages_validation::check_and_lint; // Ensure you have this at the top
+
```
Comment (kkawula) [inline crates/forge/tests/code_quality.rs:3]: What is the idea behind this?

**Review by kkawula — APPROVED** [review]

File: crates/forge/tests/code_quality.rs (hunk 25 above)
Comment (franciszekjob) [reply crates/forge/tests/code_quality.rs]: Leftover, removed 😅

File: crates/forge/tests/e2e/templates.rs (hunk 24 above)
Comment (cptartur) [reply crates/forge/tests/e2e/templates.rs:30]: Test case can have a reference to the template and a path to it. But maybe that's more complicated than the current solution

File: crates/forge/tests/code_quality.rs [hunk 26]
```diff
@@ -0,0 +1,18 @@
...
+    let package_path: Utf8PathBuf = std::env::current_dir()
+        .expect("Failed to get current directory")
+        .ancestors()
+        .nth(2)
+        .expect("Failed to get grandparent directory")
+        .join("snforge_std")
+        .canonicalize()
+        .expect("Failed to canonicalize path")
+        .try_into()
+        .expect("Failed to convert to Utf8PathBuf");
```
Comment (cptartur) [inline crates/forge/tests/code_quality.rs]: Why not just provide this path directly if the working directory of tests is stable?

```suggestion
    let package_path = Utf8PathBuf::from("../../snforge_std")
        .canonicalize()
        .unwrap()
        .try_into()
        .unwrap();
```

File: crates/sncast/tests/code_quality.rs [hunk 27]
```diff
@@ -0,0 +1,18 @@
+use camino::Utf8PathBuf;
+use packages_validation::check_and_lint;
+
+#[test]
+fn validate_sncast_std() {
+    let package_path: Utf8PathBuf = std::env::current_dir()
```
Comment (cptartur) [inline crates/sncast/tests/code_quality.rs]: Same here

File: crates/forge/tests/e2e/templates.rs (hunk 24 above)
Comment (franciszekjob) [reply crates/forge/tests/e2e/templates.rs:30]: I would stay with current one tbh.

**Review by cptartur — APPROVED** [review]
