### PR TITLE
Handle requirements check when tools not installed

### LINKED ISSUE #2807: Handle missing requirements in snforge compatibility check
Currently, snforge compatibility check displays nice output only when incorrect version of a requirement is installed. In case it is missing entirely, `Failed to run version command for {name}` error is bubbled.

Update compatibility check so it displays missing requirements similarly as incompatible. 
E.g. `"❌ {} is not installed"` or similar.

### PR DESCRIPTION
**Pull request by ddoktorski**
Closes #2807 

## Introduced changes

- Display a formatted message when `--version` command fails instead of returning an immediate error

### CODE REVIEW

File: crates/forge/src/compatibility_check.rs [hunk 1]
```diff
@@ -46,48 +93,21 @@ impl<'a> RequirementsChecker<'a> {
...
-                .is_none_or(|minimal_recommended_version| version >= *minimal_recommended_version);
-
-            let min_version_to_display = requirement
-                .minimal_recommended_version
-                .as_ref()
-                .unwrap_or(&requirement.minimal_version);
-
-            let command_output = if !is_valid {
+            if !is_valid {
                 all_valid = false;
```
Comment (franciszekjob) [inline crates/forge/src/compatibility_check.rs:104]: nit: We can simplify this:

```rust
all_valid &= is_valid;
```

File: crates/forge/src/compatibility_check.rs [hunk 2]
```diff
@@ -105,11 +125,13 @@ pub fn create_version_parser<'a>(name: &'a str, pattern: &'a str) -> Box<Version
...
-        .borrow_mut()
-        .output()
-        .with_context(|| format!("Failed to run version command for {name}"))?;
+fn get_version(command: &RefCell<Command>, parser: &VersionParser) -> Result<Version> {
+    let raw_version = get_raw_version(command)?;
+    parser(&raw_version)
+}
+
+fn get_raw_version(command: &RefCell<Command>) -> Result<String> {
+    let raw_current_version = command.borrow_mut().output_checked()?;
```
Comment (franciszekjob) [inline crates/forge/src/compatibility_check.rs:134]: 1. Let's inline `get_raw_version`, it's very short and used just once (inside `get_version`):

```rust
fn get_version(command: &RefCell<Command>, parser: &VersionParser) -> Result<Version> {
    let raw_current_version = command.borrow_mut().output_checked()?;
    let raw_version = String::from_utf8_lossy(&raw_current_version.stdout)
        .trim()
        .to_string();
    parser(&raw_version)
}
```

2. `get_version` should be a method of `Requirement`.

File: .github/workflows/ci.yml [hunk 3]
```diff
@@ -106,17 +106,20 @@ jobs:
...
+  test-requirements-check-special-conditions:
+    name: Test requirements check special conditions
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - uses: dtolnay/rust-toolchain@stable
       - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab
+      - uses: software-mansion/setup-universal-sierra-compiler@v1
+
+      - run: cargo test --package forge --features no_scarb_installed --lib compatibility_check::tests::fail_to_run_command
```
Comment (franciszekjob) [inline .github/workflows/ci.yml:118]: 😅 
```suggestion
      - run: cargo test --package forge --features no_scarb_installed --lib compatibility_check::tests::failing_tool_not_installed
```

**Review by franciszekjob — APPROVED** [review]

**Review by kkawula — APPROVED** [review]
