### PR TITLE
Make rpc url optional for `show-config` command

### LINKED ISSUE #2644: Running show-config w/o profile or full sncast yields uninformative result
### Which component is your bug related to?

sncast

### Foundry Version

0.32.0

### What operating system are you using?

Linux

### What system architecture are you using?

x86

### What happened

I create a new project and run `sncast show-config`

The result is 
`Error: RPC url not passed nor found in snfoundry.toml`

This is not very informative.

Even if I have a URL filled for some profile, the same error appears, unless a `-p` flag is passed

```
[sncast.myprofile1]                                    # Define a profile name
url = "http://127.0.0.1:5050/"                         # Url of the RPC provider
```

An error telling me to select a profile would be more informative.

Updating the `snfoundry.toml` to use `default` profile instead of `myprofile` would at least avoid this if there is only one profile in use

### Trace

_No response_

### Is there an existing issue for this?

- [ ] I have searched the existing issues and verified no issue exits for this problem.

### PR DESCRIPTION
**Pull request by ddoktorski**
Closes #2644 

## Introduced changes

- Do not require rpc url for `show-config` command to work
- Added missing `show_explorer_links` field to the `ShowConfigResponse`

## Checklist

- [X] Linked relevant issue
- [X] Updated relevant documentation
- [X] Added relevant tests
- [X] Performed self-review of the code
- [X] Added changes to `CHANGELOG.md`

### CODE REVIEW

File: crates/sncast/src/response/structs.rs [hunk 1]
```diff
@@ -107,13 +107,14 @@ impl CommandResponse for MulticallNewResponse {}
...
     pub profile: Option<String>,
-    pub chain_id: String,
+    pub chain_id: Option<String>,
     pub rpc_url: Option<String>,
     pub account: Option<String>,
     pub accounts_file_path: Option<Utf8PathBuf>,
     pub keystore: Option<Utf8PathBuf>,
     pub wait_timeout: Option<Decimal>,
     pub wait_retry_interval: Option<Decimal>,
+    pub show_explorer_links: bool,
```
Comment (ddoktorski) [inline crates/sncast/src/response/structs.rs:117]: Note: We can also add a `block_explorer` field here, but it doesn't seem crucial to me.

Comment (cptartur) [reply crates/sncast/src/response/structs.rs:117]: Can be done in a separate task. Can you create one?

**Review by cptartur — APPROVED** [review]

File: crates/sncast/src/response/structs.rs (hunk 1 above)
Comment (ddoktorski) [reply crates/sncast/src/response/structs.rs:117]: https://github.com/foundry-rs/starknet-foundry/issues/2711
