### PR TITLE
test: data-transformer ambiguous enum

### LINKED ISSUE #2553: Add tests with ambiguous enum to data transformer
## Component the issue is related to
Cast - data transformer

## Issue
Data transformer should throw an error in case of passing an *ambiguous* struct or enum name.
We test this behaviour for structs but tests for enums are lacking.
One need to create a new contract which uses an external enum and defines its own with identical name at the same time.

There is already an existing test for structs that can be seen here

https://github.com/foundry-rs/starknet-foundry/blob/5306b4375c5b01653d295fef8d4d0f58ea071da8/crates/data-transformer/tests/integration.rs#L578

Create a new test that tests ambigous enums, in similar manner as the test linked above.

## Example and explanation:
Suppose we use Alexandria's `BitArray` type in our contract. We define our own struct with the same name and use it to.
```rs
#[starknet::contract]
mod Contract {
    /* ... */

    use alexandria_data_structures;

    pub struct BitArray { };

    fn method(
        self: @ContractState,
        external_type_array: alexandria_data_structures::bit_array::BitArray,
        our_own_type_array: BitArray
    ) { }
}
```

When calling `method` from CLI, we need to refer to these structures using paths:
```shell
sncast [...] --calldata "alexandria_data_structures::bit_array::BitArray { ... }" "data_transformer_contract::BitArray{ ... }"
```

When called without paths, Cast will throw an error:
```
Error while processing Cairo-like calldata:

Caused by:
    Found more than one struct "BitArray" in ABI, please specify a full path to the item
```

### PR DESCRIPTION
**Pull request by khayss**
Closes #2553 

## Introduced changes

- Add test for ambiguous enum to `data-transformer`.

## Checklist

- [x] Linked relevant issue
- [ ] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [ ] Added changes to `CHANGELOG.md`

### CODE REVIEW

**Comment by khayss** [comment]
This is a draft. I have some questions to continue with the issue.

**Comment by cptartur** [comment]
Hey @khayss, what's the status of this? If you have questions please ask them here or in the telegram, https://t.me/starknet_foundry_support

If you are no longer working on the issue, please let us know so we can reassign.

**Comment by khayss** [comment]
Hello @cptartur, I'm working on this. I already reached out on Telegram and will be updates soon.

**Comment by khayss** [comment]
Hey @cptartur 
I have added the test. It's passing. Kindly review and let me know any changes to make or add.

**Comment by khayss** [comment]
@cptartur any update on this?

File: crates/data-transformer/tests/integration.rs [hunk 1]
```diff
@@ -663,3 +663,36 @@ async fn test_happy_case_contract_constructor() -> anyhow::Result<()> {
 
     Ok(())
 }
+
```
Comment (cptartur) [inline crates/data-transformer/tests/integration.rs:666]: In this file, above there are lines 

```
// TODO add similar test but with enums (Issue #2553)
//  - take existing contract code
//  - find/create a library with an enum
//  - add to project as a dependency
//  - create enum with the same name in your contract code
```

Please remove them as your PR resolves the TODO.

**Review by cptartur — APPROVED** [review]
Please address my comments, otherwise looks good 👍

File: crates/data-transformer/tests/integration.rs [hunk 2]
```diff
@@ -663,3 +663,36 @@ async fn test_happy_case_contract_constructor() -> anyhow::Result<()> {
...
+#[tokio::test]
+async fn test_external_enum_function_ambiguous_struct_name_cairo_expression_input() {
```
[the remark this answers is not in the document]
Comment (khayss) [reply crates/data-transformer/tests/integration.rs]: Resolved this.

File: crates/data-transformer/tests/integration.rs (hunk 1 above)
Comment (khayss) [reply crates/data-transformer/tests/integration.rs:661]: Removed the TODO

**Comment by khayss** [comment]
I've implemented the requested changes in the latest commit.

File: crates/data-transformer/tests/integration.rs [hunk 3]
```diff
@@ -663,3 +658,36 @@ async fn test_happy_case_contract_constructor() -> anyhow::Result<()> {
...
+#[tokio::test]
+async fn test_external_enum_function_ambiguous_enum_name_cairo_expression_input() {
+    // https://sepolia.starkscan.co/class/0x019ea00ebe2d83fb210fbd6f52c302b83c69e3c8c934f9404c87861e9d3aebbc#code
+    let test_class_hash: Felt = Felt::from_hex_unchecked(
+        "0x019ea00ebe2d83fb210fbd6f52c302b83c69e3c8c934f9404c87861e9d3aebbc",
+    );
+
+    let client = JsonRpcClient::new(HttpTransport::new(
+        Url::parse("http://188.34.188.184:7070/rpc/v0_7").unwrap(),
+    ));
```
Comment (kkawula) [inline crates/data-transformer/tests/integration.rs:671]: lets use constant instead 
https://github.com/foundry-rs/starknet-foundry/blob/master/crates/shared/src/test_utils/node_url.rs#L8-L11

**Review by kkawula — APPROVED** [review]

File: crates/data-transformer/tests/integration.rs (hunk 3 above)
Comment (khayss) [reply crates/data-transformer/tests/integration.rs]: I have made the requested changes in the most recent commits

**Review by cptartur — APPROVED** [review]
