### PR TITLE
Fix resources from syscalls in nested calls

### LINKED ISSUE #3473: Resolve problem with duplicated resources for syscalls in nested calls
### Current State

Currently, resources from syscalls in nested calls are duplicated. For instance:

- contract A calls function xyz in contract B
- function xyz looks as follows
```rust
...
use core::sha256::compute_sha256_u32_array;
...

fn xyz() {
...
   let _hash = compute_sha256_u32_array(array![0x68656c6c], 0x6f, 1);
...
}
```
`compute_sha256_u32_array` uses `Sha256ProcessBlock` syscall under the hood. Considering cost of `Sha256ProcessBlock` in [versioned constants for 0.13.5](https://github.com/starkware-libs/sequencer/blob/92ca79821b5b370d0527d717cb1c47d57b96d24d/crates/blockifier/resources/blockifier_versioned_constants_0_13_5.json#L367), it should use 1115 bitwise builtins.

- instead, we're getting 2230 builtins (which is 2 * 1115)

Related with https://github.com/foundry-rs/starknet-foundry/issues/3413

### Objective

Resolve problem with duplicated resources for syscalls in nested calls

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by franciszekjob**
Closes #3473 

## Introduced changes

Fix bug calculation of resources from nested calls syscalls. The reason of malformed calculations was that during subtracting syscalls' resources in `remove_syscall_resources_and_exit_non_error_call`, they were only from current call and didn't include the ones from nested calls.

## Checklist

- [x] Linked relevant issue
- [x] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

### CODE REVIEW

File: crates/cheatnet/src/runtime_extensions/call_to_blockifier_runtime_extension/execution/cairo1_execution.rs [hunk 1]
```diff
@@ -124,9 +127,18 @@ pub(crate) fn execute_entry_point_call_cairo1(
             .register_error(class_hash, pcs);
     }
 
+    let mut syscall_usage_vm_resources = SyscallUsageMap::default();
+    let mut syscall_usage_sierra_gas = SyscallUsageMap::default();
+
+    match tracked_resource {
+        TrackedResource::CairoSteps => syscall_usage_vm_resources.clone_from(&syscall_usage),
+        TrackedResource::SierraGas => syscall_usage_sierra_gas.clone_from(&syscall_usage),
+    }
```
Comment (cptartur) [inline crates/cheatnet/src/runtime_extensions/call_to_blockifier_runtime_extension/execution/cairo1_execution.rs]: It could be rewritten so that variables don't have to be mutable

```rust
    let (syscall_usage_vm_resources, syscall_usage_sierra_gas) = match tracked_resource {
        TrackedResource::CairoSteps => (syscall_usage, SyscallUsageMap::default()),
        TrackedResource::SierraGas => (SyscallUsageMap::default(), syscall_usage),
    };
```

Though I'm not sure if that's actually better or not.

**Review by cptartur — APPROVED** [review]
Logic wise looks good, see me comment about possible refactoring

File: crates/cheatnet/src/runtime_extensions/call_to_blockifier_runtime_extension/execution/cairo1_execution.rs (hunk 1 above)
Comment (franciszekjob) [reply crates/cheatnet/src/runtime_extensions/call_to_blockifier_runtime_extension/execution/cairo1_execution.rs]: Applied 👍

File: crates/cheatnet/src/runtime_extensions/call_to_blockifier_runtime_extension/execution/deprecated/cairo0_execution.rs [hunk 2]
```diff
@@ -80,9 +81,16 @@ pub(crate) fn execute_entry_point_call_cairo0(
         n_total_args,
     )?;
 
+    let (syscall_usage_vm_resources, syscall_usage_sierra_gas) =
+        match execution_result.tracked_resource {
+            TrackedResource::CairoSteps => (syscall_usage, SyscallUsageMap::default()),
+            TrackedResource::SierraGas => (SyscallUsageMap::default(), syscall_usage),
+        };
```
Comment (ddoktorski) [inline crates/cheatnet/src/runtime_extensions/call_to_blockifier_runtime_extension/execution/deprecated/cairo0_execution.rs]: It is not possible to track Sierra gas for Cairo 0, so we don't need this logic here

File: crates/cheatnet/src/runtime_extensions/call_to_blockifier_runtime_extension/execution/entry_point.rs [hunk 3]
```diff
@@ -309,22 +315,43 @@ fn remove_syscall_resources_and_exit_non_error_call(
     let mut resources = call_info.resources.clone();
     let mut gas_consumed = call_info.execution.gas_consumed;
 
+    // Remove resources consumed by syscalls from the current call
+    // `syscall_usage_vm_resources` and `syscall_usage_sierra_gas` are flat, meaning they only include syscalls from the specific call
     match current_tracked_resource {
```
Comment (ddoktorski) [inline crates/cheatnet/src/runtime_extensions/call_to_blockifier_runtime_extension/execution/entry_point.rs]: nit: One of the values `syscall_usage_vm_resources` or `syscall_usage_sierra_gas` is always empty, so we can remove the `match` and it should work the same

File: crates/cheatnet/src/runtime_extensions/forge_runtime_extension/mod.rs [hunk 4]
```diff
@@ -769,7 +810,7 @@ pub fn get_all_used_resources(
 
     let mut execution_resources = top_call.borrow().used_execution_resources.clone();
     let mut sierra_gas_consumed = top_call.borrow().gas_consumed;
-    let top_call_syscalls = top_call.borrow().used_syscalls.clone();
+    let top_call_syscalls = top_call.borrow().get_total_used_syscalls();
```
Comment (ddoktorski) [inline crates/cheatnet/src/runtime_extensions/forge_runtime_extension/mod.rs:813]: This seems incorrect, instead we should rather simply add syscall resources to the respective resource type without making a distinction between different tracked resource, something along the lines of:
```rust
execution_resources = add_syscall_execution_resources(
    versioned_constants,
    &execution_resources,
    &top_call.borrow().used_syscalls_vm_resources,
);
sierra_gas_consumed += get_syscalls_gas_consumed(
    &top_call.borrow().used_syscalls_sierra_gas,
    versioned_constants,
);
```

**Review by ddoktorski — CHANGES_REQUESTED** [review]

**Review by ddoktorski — APPROVED** [review]
🙏
