### PR TITLE
Change backtrace warning

### LINKED ISSUE #3272: Update backtrace warning
### Current State

Update the warning to include information about the necessary `Scarb` version once there is an official release that supports backtrace hint.

### Objective

Update backtrace warning

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ksew1**
Closes #3272

commit-id:0744f312

### CODE REVIEW

File: crates/forge/src/warn.rs [hunk 1]
```diff
@@ -202,10 +202,20 @@ pub(crate) fn warn_if_backtrace_without_panic_hint(scarb_metadata: &Metadata, ui
             });
 
         if !is_panic_backtrace_set {
-            ui.println(
-                &WarningMessage::new("To get accurate backtrace results, it is required to use the configuration available in the latest Cairo version. \
-                For more details, please visit https://foundry-rs.github.io/starknet-foundry/snforge-advanced-features/backtrace.html"
-            ));
+            let message = formatdoc! {
+                "Scarb.toml should be run on scarb 2.12.* or latter and have the following Cairo compiler configuration to run backtrace:
```
Comment (franciszekjob) [inline crates/forge/src/warn.rs]:
```suggestion
                "scarb version should be 2.12.* and `Scarb.toml` should have the following Cairo compiler configuration to run backtrace:
```

**Review by franciszekjob — APPROVED** [review]

File: crates/forge/src/warn.rs [hunk 2]
```diff
@@ -202,10 +202,20 @@ pub(crate) fn warn_if_backtrace_without_panic_hint(scarb_metadata: &Metadata, ui
             });
 
         if !is_panic_backtrace_set {
-            ui.println(
-                &WarningMessage::new("To get accurate backtrace results, it is required to use the configuration available in the latest Cairo version. \
-                For more details, please visit https://foundry-rs.github.io/starknet-foundry/snforge-advanced-features/backtrace.html"
-            ));
+            let message = formatdoc! {
+                "scarb version should be 2.12.* and `Scarb.toml` should have the following Cairo compiler configuration to run backtrace:
```
Comment (ddoktorski) [inline crates/forge/src/warn.rs]:
```suggestion
                "Scarb version should be 2.12 or higher and `Scarb.toml` should have the following Cairo compiler configuration to run backtrace:
```

File: crates/forge/src/warn.rs [hunk 3]
```diff
@@ -202,10 +202,20 @@ pub(crate) fn warn_if_backtrace_without_panic_hint(scarb_metadata: &Metadata, ui
...
+
+                [profile.{profile}.cairo]
+                unstable-add-statements-functions-debug-info = true
+                unstable-add-statements-code-locations-debug-info = true
+                panic-backtrace = true # only for scarb 2.12.* or later
+                ... other entries ...
+
+                To get accurate backtrace results.
```
Comment (ddoktorski) [inline crates/forge/src/warn.rs]: It's easy to overlook when it's placed at the end

Comment (ksew1) [reply crates/forge/src/warn.rs]: Moved to start

File: crates/forge/tests/e2e/backtrace.rs [hunk 4]
```diff
@@ -36,7 +36,16 @@ fn test_backtrace() {
...
-            [WARNING] To get accurate backtrace results, it is required to use the configuration available in the latest Cairo version. For more details, please visit https://foundry-rs.github.io/starknet-foundry/snforge-advanced-features/backtrace.html
+            [WARNING] Scarb version should be 2.12 or higher and `Scarb.toml` should have the following Cairo compiler configuration to run backtrace:
+
+            [profile.dev.cairo]
+            unstable-add-statements-functions-debug-info = true
+            unstable-add-statements-code-locations-debug-info = true
+            panic-backtrace = true # only for scarb 2.12.* or later
+            ... other entries ...
+
+            To get accurate backtrace results.
```
Comment (ddoktorski) [inline crates/forge/tests/e2e/backtrace.rs]: It should be updated also here

**Review by ddoktorski — APPROVED** [review]
