### PR TITLE
Fix syscall ptr bug

### LINKED ISSUE #659: Calling a contract and then using `get_block_number` fails
still fails if trying to use `get_block_number` and mock calls at same time:

Screenshot 2023-09-13 at 18 58 24

_Originally posted by @delaaxe in https://github.com/foundry-rs/starknet-foundry/issues/645#issuecomment-1717906110_

### PR DESCRIPTION
**Pull request by MaksymilianDemitraszek**
Closes #659

## Introduced changes

- Increments syscall_ptr of the test execution syscall handler when writing to syscall 
- Removed unnecessary implementation
- Slightly refactored buffer reading (we do it only in one place so I restrained from abstracting it too much)

## Checklist

- [x] Linked relevant issue
- [x] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

### CODE REVIEW

**Comment by cptartur** [comment]
Is the work on this going to be continued in the future or should this PR be closed?

**Comment by MaksymilianDemitraszek** [comment]
cc @abulenok if you are interested

File: crates/forge/src/test_execution_syscall_handler.rs [hunk 1]
```diff
@@ -698,29 +677,58 @@ fn execute_call_contract(
...
 
     let calldata = buffer.next_arr().unwrap();
-
-    let call_result = call_contract(
-        blockifier_state,
-        cheatnet_state,
-        &contract_address,
-        &entry_point_selector,
-        &calldata,
+    cheatable_syscall_handler.syscall_handler.syscall_ptr += (buffer.ptr - system_ptr).unwrap();
```
Comment (Arcticae) [inline crates/forge/src/test_execution_syscall_handler.rs:680]: This is a confusing place to increment the syscall pointer

File: crates/forge/src/test_execution_syscall_handler.rs [hunk 2]
```diff
@@ -651,45 +649,26 @@ fn execute_syscall(
...
-    let sc_response = SyscallResponseWrapper::Success {
-        gas_counter: gas_counter - GET_BLOCK_HASH_GAS_COST,
-        response: GetBlockHashResponse {
-            block_hash: BlockHash(StarkFelt::from(0_u32)),
-        },
-    };
-    sc_response.write(vm, system_ptr)?;
-    Ok(())
+struct CallContractArgs {
+    _selector: Felt252,
```
Comment (Arcticae) [inline crates/forge/src/test_execution_syscall_handler.rs:657]: Why bother with that one if it's not used?

File: crates/forge/src/test_execution_syscall_handler.rs [hunk 3]
```diff
@@ -651,45 +649,26 @@ fn execute_syscall(
...
+    gas_counter: usize,
```
Comment (Arcticae) [inline crates/forge/src/test_execution_syscall_handler.rs:658]: Why is it `usize` and not other type?

Comment (Arcticae) [reply crates/forge/src/test_execution_syscall_handler.rs:658]: I've encountered gas counters with u64/f64 values so far 😬

File: crates/cheatnet/src/execution/syscalls.rs [hunk 4]
```diff
@@ -278,24 +277,64 @@ impl CheatableSyscallHandler<'_> {
...
                 constants::CALL_CONTRACT_GAS_COST,
             );
         } else if SyscallSelector::Deploy == selector {
+            let StarknetHint::SystemCall { system: syscall } = hint else {
+                return Err(HintError::CustomHint(
+                    "Test functions are unsupported on starknet.".into(),
+                ));
+            };
+            let initial_syscall_ptr = get_ptr_from_res_operand_unchecked(vm, syscall);
+            self.verify_syscall_ptr(initial_syscall_ptr)?;
```
Comment (Arcticae) [inline crates/cheatnet/src/execution/syscalls.rs:329]: There is a lot of repetition here, can we somehow clean this up?

File: crates/cheatnet/src/execution/syscalls.rs [hunk 5]
```diff
@@ -278,24 +277,64 @@ impl CheatableSyscallHandler<'_> {
...
+
             // Increment, since the selector was peeked into before
             self.syscall_handler.syscall_ptr += 1;
+
+            if selector != SyscallSelector::Keccak {
```
Comment (Arcticae) [inline crates/cheatnet/src/execution/syscalls.rs:334]: ^

**Review by Arcticae — CHANGES_REQUESTED** [review]

File: crates/forge/src/test_execution_syscall_handler.rs (hunk 2 above)
Comment (MaksymilianDemitraszek) [reply crates/forge/src/test_execution_syscall_handler.rs:657]: For completeness, I assume if somebody will need it in the future won't create additional abstraction to use it.

File: crates/forge/src/test_execution_syscall_handler.rs (hunk 1 above)
Comment (MaksymilianDemitraszek) [reply crates/forge/src/test_execution_syscall_handler.rs:704]: Discussed offline, we don't have any idea to improve upon it

File: crates/cheatnet/src/execution/syscalls.rs (hunk 4 above)
Comment (MaksymilianDemitraszek) [reply crates/cheatnet/src/execution/syscalls.rs:342]: I will tackle those in a separate PR https://github.com/orgs/foundry-rs/projects/3/views/2?pane=issue&itemId=40983148 as there is more extensive work to do there.

File: crates/cheatnet/src/execution/syscalls.rs (hunk 5 above)
Comment (MaksymilianDemitraszek) [reply crates/cheatnet/src/execution/syscalls.rs:347]: https://github.com/orgs/foundry-rs/projects/3/views/2?pane=issue&itemId=40983148

File: crates/forge/src/test_execution_syscall_handler.rs (hunk 3 above)
Comment (MaksymilianDemitraszek) [reply crates/forge/src/test_execution_syscall_handler.rs:682]: Good call, i just copied existing code here but indeed we should parse u64 https://github.com/orgs/foundry-rs/projects/3/views/2?pane=issue&itemId=40983148

File: crates/cheatnet/src/execution/syscalls.rs [hunk 6]
```diff
@@ -291,24 +290,64 @@ impl CheatableSyscallHandler<'_> {
...
```
Comment (abulenok) [inline crates/cheatnet/src/execution/syscalls.rs:325]: The selector is already `!= Keccak` here

File: crates/cheatnet/src/execution/syscalls.rs (hunk 4 above)
Comment (MaksymilianDemitraszek) [reply crates/cheatnet/src/execution/syscalls.rs:342]: I did some refactors here because of clippy, I still want to clean it up further though

File: crates/cheatnet/src/execution/syscalls.rs (hunk 6 above)
Comment (MaksymilianDemitraszek) [reply crates/cheatnet/src/execution/syscalls.rs]: https://github.com/foundry-rs/starknet-foundry/pull/680/commits/17bd90929784720a4bd1eb6692ce5108c409c005

File: crates/cheatnet/src/execution/syscalls.rs (hunk 5 above)
Comment (MaksymilianDemitraszek) [reply crates/cheatnet/src/execution/syscalls.rs]: https://github.com/foundry-rs/starknet-foundry/pull/680/commits/be56df31c0850bddff991e82c87cf608316dc7ed

File: crates/cheatnet/src/execution/syscalls.rs (hunk 4 above)
Comment (MaksymilianDemitraszek) [reply crates/cheatnet/src/execution/syscalls.rs]: https://github.com/foundry-rs/starknet-foundry/pull/680/commits/be56df31c0850bddff991e82c87cf608316dc7ed

File: crates/cheatnet/src/execution/syscalls.rs [hunk 7]
```diff
@@ -228,38 +227,36 @@ fn felt_from_ptr_immutable(
...
-
             // Increment, since the selector was peeked into before
             self.syscall_handler.syscall_ptr += 1;
-
-            if selector != SyscallSelector::Keccak {
-                self.syscall_handler
-                    .increment_syscall_count_by(&selector, 1);
-            }
+            self.syscall_handler
+                .increment_syscall_count_by(&selector, 1);
```
Comment (piotmag769) [inline crates/cheatnet/src/execution/syscalls.rs:259]: Was it the main reason why the bug occurred?

File: crates/forge/src/test_execution_syscall_handler.rs [hunk 8]
```diff
@@ -675,76 +673,86 @@ fn execute_syscall(
...
             "Replace class can't be used in tests".to_string(),
         ))),
-        DeprecatedSyscallSelector::GetBlockHash => {
-            execute_get_block_hash(
-                vm,
-                &mut system_ptr.clone(),
-                cheatable_syscall_handler.cheatnet_state,
-            )?;
-            Ok(())
-        }
```
[the remark this answers is not in the document]
Comment (MaksymilianDemitraszek) [reply crates/forge/src/test_execution_syscall_handler.rs:685]: Because it is executed by blockifiers syscall handler.
`blockifier/crates/blockifier/src/execution/syscalls/mod.rs::get_block_hash`

**Review by Arcticae — APPROVED** [review]
