### PR TITLE
Add correct class hashes to tests and fix get_class_hash impl

### LINKED ISSUE #689: Add a test that verifies `class_hash`es are calculated correctly
We only verify that `class_hash` is not 0, but there is no test that actually compares the calculated value agains an expected, precalculated one. This way we can have values for class hashes that are completely inconsistent with starknet but not be aware of it at all.

### PR DESCRIPTION
**Pull request by abulenok**
Closes #689 

## Introduced changes

- Add expected class hashes to `declare` tests. Class hashes are obtained by declaring contracts with `sncast`
- Fix `get_class_hash` implementation

## Checklist

- [x] Linked relevant issue
- [ ] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [ ] Added changes to `CHANGELOG.md`

### CODE REVIEW

File: crates/cheatnet/src/cheatcodes/declare.rs [hunk 1]
```diff
@@ -71,14 +69,8 @@ impl BlockifierState<'_> {
...
-    let sierra_class: ContractClass = serde_json::from_str(sierra_contract)?;
-    let abi_flattened = sierra_class.abi.unwrap().json();
-    let mut sierra_contract_map: HashMap<String, Value> = serde_json::from_str(sierra_contract)?;
-    sierra_contract_map.insert("abi".to_string(), Value::String(abi_flattened));
-    let sierra_contract = serde_json::to_string_pretty(&sierra_contract_map)?;
-
-    let sierra_class: FlattenedSierraClass = serde_json::from_str(&sierra_contract)?;
-    let class_hash = sierra_class.class_hash();
+    let sierra_class: SierraClass = serde_json::from_str(sierra_contract)?;
+    let class_hash = sierra_class.class_hash().unwrap();
```
Comment (piotmag769) [inline crates/cheatnet/src/cheatcodes/declare.rs:73]: `expect` with an error message would be better

File: crates/cheatnet/tests/cheatcodes/declare.rs [hunk 2]
```diff
@@ -1,8 +1,15 @@
...
 use cheatnet::cheatcodes::{CheatcodeError, EnhancedHintError};
 use conversions::StarknetConversions;
+use starknet_api::core::ClassHash;
+use starknet_api::hash::StarkFelt;
+use starknet_api::stark_felt;
+
+static HELLO_STARKNET_CLASS_HASH: &str =
+    "0x298f80e468953d1e65314b6bc63347c7a3fe454a89c2b15387dd52ee281d103";
+static CONSTRUCTOR_SIMPLE_CLASS_HASH: &str =
+    "0x02dbeae7583f3dd4af0bc2da4d58611433165fec7e31245bfa2f1378fbff6a4c";
```
Comment (piotmag769) [inline crates/cheatnet/tests/cheatcodes/declare.rs:12]: Calculated using starknet py I guess?

**Review by piotmag769 — APPROVED** [review]

File: crates/cheatnet/tests/cheatcodes/declare.rs (hunk 2 above)
Comment (abulenok) [reply crates/cheatnet/tests/cheatcodes/declare.rs:12]: with `sn_cast`, mentioned it in PR description

File: crates/cheatnet/src/cheatcodes/declare.rs (hunk 1 above)
Comment (abulenok) [reply crates/cheatnet/src/cheatcodes/declare.rs]: Added error propagation since `get_class_hash` returns `Result`

File: crates/cheatnet/src/cheatcodes/declare.rs [hunk 3]
```diff
@@ -71,14 +69,8 @@ impl BlockifierState<'_> {
...
 
 fn get_class_hash(sierra_contract: &str) -> Result<ClassHash> {
-    let sierra_class: ContractClass = serde_json::from_str(sierra_contract)?;
-    let abi_flattened = sierra_class.abi.unwrap().json();
-    let mut sierra_contract_map: HashMap<String, Value> = serde_json::from_str(sierra_contract)?;
-    sierra_contract_map.insert("abi".to_string(), Value::String(abi_flattened));
-    let sierra_contract = serde_json::to_string_pretty(&sierra_contract_map)?;
-
-    let sierra_class: FlattenedSierraClass = serde_json::from_str(&sierra_contract)?;
-    let class_hash = sierra_class.class_hash();
```
Comment (war-in) [inline crates/cheatnet/src/cheatcodes/declare.rs:81]: What happened here before? Did we extract abi and then insert it again? Does anyone have an idea?

**Review by war-in — APPROVED** [review]

File: crates/cheatnet/src/cheatcodes/declare.rs (hunk 3 above)
Comment (piotmag769) [reply crates/cheatnet/src/cheatcodes/declare.rs:81]: cc @cptartur

File: crates/cheatnet/tests/cheatcodes/declare.rs [hunk 4]
```diff
@@ -1,8 +1,15 @@
...
 use crate::common::{get_contracts, state::create_cached_state};
-use cairo_felt::Felt252;
 use cheatnet::cheatcodes::{CheatcodeError, EnhancedHintError};
 use conversions::StarknetConversions;
+use starknet_api::core::ClassHash;
+use starknet_api::hash::StarkFelt;
+use starknet_api::stark_felt;
+
+static HELLO_STARKNET_CLASS_HASH: &str =
+    "0x298f80e468953d1e65314b6bc63347c7a3fe454a89c2b15387dd52ee281d103";
```
Comment (MaksymilianDemitraszek) [inline crates/cheatnet/tests/cheatcodes/declare.rs:10]: Oh I think I misguided you, I thought you mean hardcoding declared contracts in cairo code as those stay on chain forever. In such case as here it will change with each sierra version bump.

Comment (MaksymilianDemitraszek) [reply crates/cheatnet/tests/cheatcodes/declare.rs:10]: I think it is still good to have such test, though it will be pain to re-calculate it each time with sncast. Maybe we could use `starknet.rs` to automate it here?

File: crates/cheatnet/src/cheatcodes/declare.rs (hunk 3 above)
Comment (cptartur) [reply crates/cheatnet/src/cheatcodes/declare.rs:81]: Scarb artifacts represent ABIs as json structures, where blockifier expected the ABI to be a flat string (this is how actual network works as well for cairo1 contracts), so I had to flatten the abi, otherwise serialization would fail.

I see a different type is used for sierra class now that seems to accept abis like this.

**Review by Arcticae — APPROVED** [review]

File: crates/cheatnet/tests/cheatcodes/declare.rs (hunk 4 above)
Comment (MaksymilianDemitraszek) [reply crates/cheatnet/tests/cheatcodes/declare.rs:10]: It is ok to merge this one and add another issue for it

Comment (abulenok) [reply crates/cheatnet/tests/cheatcodes/declare.rs:10]: added https://github.com/foundry-rs/starknet-foundry/issues/929
