### PR TITLE
Fix counting syscalls 

### LINKED ISSUE #1631: Count syscalls properly
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

Syscalls like Deploy / CallContract are currently not counted properly due to when deploying / calling contract through cheatcode / dispatcher.

They probably should be manually incremented here:
https://github.com/foundry-rs/starknet-foundry/blob/2f3775b273936616cea3c5ad842adc4749b120fa/crates/cheatnet/src/runtime_extensions/call_to_blockifier_runtime_extension/mod.rs#L145

---

Reference:
https://github.com/foundry-rs/starknet-foundry/blob/85728f429b0a91e79519b16ad153ccdc2dd4ddf1/crates/forge/tests/data/erc20_package/tests/test_complex.cairo#L30

### PR DESCRIPTION
**Pull request by war-in**
Closes #1631

## Introduced changes

-

## Checklist

- [x] Linked relevant issue
- [x] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

### CODE REVIEW

**Review by piotmag769 — COMMENTED** [review]
The logic is fine

File: crates/forge/tests/integration/gas.rs [hunk 1]
```diff
@@ -428,8 +427,8 @@ fn contract_ec_op_cost() {
 
     assert_passed!(result);
     // 1101 = cost of deploy (see snforge_std_deploy_cost test)
-    // 6 = cost of single ec_op builtin
-    assert_gas!(result, "contract_ec_op_cost", 1101 + 6);
+    // 52 = cost of 10x ec_op builtin
```
Comment (piotmag769) [inline crates/forge/tests/integration/gas.rs:430]: typo

**Review by piotmag769 — APPROVED** [review]
LGTM, should we do #1734 some time after that? This outdates the docs even more (not sure if it means starknet has their docs a bit missleading since they don't have anything about additional cost of syscalls in relation to cairo resources)
