### PR TITLE
Fix backtrace test with scarb `2.13.x`

### LINKED ISSUE #3935: Fix backtrace in Scarb 2.13.1
### Current State

Currently, one of the backtrace tests is failing https://github.com/foundry-rs/starknet-foundry/actions/runs/19397735977/job/55500183616#step:13:1916

### Objective

Verify if the failing tests is due to a bug and fix it (or fix the test)

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MKowalski8**
Closes #3935

## Introduced changes

- Fix backtrace test

## Checklist

- [x] Linked relevant issue
- [ ] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [ ] Added changes to `CHANGELOG.md`

### CODE REVIEW

**Comment by MKowalski8** [comment]
Scheduled tests have passed 

obraz

File: crates/forge/tests/e2e/backtrace.rs [hunk 1]
```diff
@@ -236,31 +236,46 @@ fn test_backtrace_panic() {
             },
         );
     } else {
+        // TODO: (#3906) Remove this once we bump minimal scarb version to 2.13.
```
Comment (cptartur) [inline crates/forge/tests/e2e/backtrace.rs]: You have a wrong issue number here

```suggestion
        // TODO: (#3909) Remove this once we bump minimal scarb version to 2.13.
```

**Review by cptartur — APPROVED** [review]

**Review by franciszekjob — APPROVED** [review]
