### PR TITLE
Fix fork caches on windows

### LINKED ISSUE #2303: Fix double locking file caches on windows
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

There seems to be a problem with file locking, double lock does not wait for acquiring but fails on the write itself:

Image

Related code:

https://github.com/foundry-rs/starknet-foundry/blob/8fa75bbdd1b0b0b80c6fc3e7fc9fa399a11a925a/crates/cheatnet/src/forking/cache.rs#L138C1-L141C1

The problem seems to be the way windows locks work in `fs2`
Related info about cross-platform locking in `fs2`: https://tikv.github.io/doc/fs2/trait.FileExt.html#notes-on-file-locks

### PR DESCRIPTION
**Pull request by cptartur**
Closes #2303

## Introduced changes

- Fixed fork caches on windows.
- Restored forking related tests on windows

## Checklist

- [x] Linked relevant issue
- [x] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

### CODE REVIEW

**Review by kkawula — APPROVED** [review]

File: crates/cheatnet/src/forking/cache.rs [hunk 1]
```diff
@@ -134,15 +134,17 @@ impl ForkCache {
     fn save(&self) {
         let mut file = OpenOptions::new()
```
Comment (Draggu) [inline crates/cheatnet/src/forking/cache.rs:135]: Probably should be stored in `ForkCache` instead of `Utf8PathBuf` to prevent using wrong handle in future

File: crates/cheatnet/src/forking/cache.rs [hunk 2]
```diff
@@ -152,6 +154,8 @@ impl ForkCache {
             fs_fork_cache_content.to_string()
         };
 
+        file.set_len(0).expect("Failed to truncate file");
```
Comment (Draggu) [inline crates/cheatnet/src/forking/cache.rs:157]: You can make separate method `.clear()` for this

File: crates/cheatnet/src/forking/cache.rs (hunk 1 above)
Comment (cptartur) [reply crates/cheatnet/src/forking/cache.rs:135]: This way we'd be keeping the file open for the duration of the program. I'd avoid changing this logic too much in this PR.

**Review by ddoktorski — APPROVED** [review]

File: crates/cheatnet/src/forking/cache.rs [hunk 3]
```diff
@@ -99,6 +99,18 @@ impl Drop for ForkCache {
     }
 }
 
+trait FileTruncateExtension {
```
Comment (Draggu) [inline crates/cheatnet/src/forking/cache.rs:102]: Use `Ext`, `Extension` has meaning in cheatnet
